/**
 * @file    types.ts
 * @brief   Core type definitions for ESEngine SDK
 */
type Entity = number;
interface Vec2 {
    x: number;
    y: number;
}
interface Vec3 {
    x: number;
    y: number;
    z: number;
}
interface Vec4 {
    x: number;
    y: number;
    z: number;
    w: number;
}
interface Quat {
    w: number;
    x: number;
    y: number;
    z: number;
}

/**
 * @file    wasm.generated.ts
 * @brief   ESEngine WASM Bindings TypeScript Definitions
 * @details Generated by EHT - DO NOT EDIT
 */

interface UVec2 {
    x: number;
    y: number;
}
interface BoxCollider {
    halfExtents: Vec2;
    offset: Vec2;
    density: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
    enabled: boolean;
}
interface CircleCollider {
    radius: number;
    offset: Vec2;
    density: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
    enabled: boolean;
}
interface CapsuleCollider {
    radius: number;
    halfHeight: number;
    offset: Vec2;
    density: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
    enabled: boolean;
}
interface LocalTransform {
    position: Vec3;
    rotation: Quat;
    scale: Vec3;
}
interface WorldTransform {
    position: Vec3;
    rotation: Quat;
    scale: Vec3;
}
interface Velocity {
    linear: Vec3;
    angular: Vec3;
}
interface SpineAnimation {
    skeletonPath: string;
    atlasPath: string;
    skin: string;
    animation: string;
    timeScale: number;
    loop: boolean;
    playing: boolean;
    flipX: boolean;
    flipY: boolean;
    color: Vec4;
    layer: number;
    skeletonScale: number;
    material: number;
    enabled: boolean;
}
interface RigidBody {
    bodyType: number;
    gravityScale: number;
    linearDamping: number;
    angularDamping: number;
    fixedRotation: boolean;
    bullet: boolean;
    enabled: boolean;
}
interface BitmapText {
    text: string;
    color: Vec4;
    fontSize: number;
    align: number;
    spacing: number;
    layer: number;
    font: number;
    enabled: boolean;
}
interface Sprite {
    texture: number;
    color: Vec4;
    size: Vec2;
    uvOffset: Vec2;
    uvScale: Vec2;
    layer: number;
    flipX: boolean;
    flipY: boolean;
    material: number;
    enabled: boolean;
}
interface Parent {
    entity: number;
}
interface Children {
}
interface Canvas {
    designResolution: UVec2;
    pixelsPerUnit: number;
    scaleMode: number;
    matchWidthOrHeight: number;
    backgroundColor: Vec4;
}
interface Camera {
    projectionType: number;
    fov: number;
    orthoSize: number;
    nearPlane: number;
    farPlane: number;
    aspectRatio: number;
    isActive: boolean;
    priority: number;
    viewportX: number;
    viewportY: number;
    viewportW: number;
    viewportH: number;
    clearFlags: number;
}
interface Registry {
    create(): Entity;
    destroy(entity: Entity): void;
    valid(entity: Entity): boolean;
    entityCount(): number;
    hasBoxCollider(entity: Entity): boolean;
    getBoxCollider(entity: Entity): BoxCollider;
    addBoxCollider(entity: Entity, component: BoxCollider): void;
    removeBoxCollider(entity: Entity): void;
    hasCircleCollider(entity: Entity): boolean;
    getCircleCollider(entity: Entity): CircleCollider;
    addCircleCollider(entity: Entity, component: CircleCollider): void;
    removeCircleCollider(entity: Entity): void;
    hasCapsuleCollider(entity: Entity): boolean;
    getCapsuleCollider(entity: Entity): CapsuleCollider;
    addCapsuleCollider(entity: Entity, component: CapsuleCollider): void;
    removeCapsuleCollider(entity: Entity): void;
    hasLocalTransform(entity: Entity): boolean;
    getLocalTransform(entity: Entity): LocalTransform;
    addLocalTransform(entity: Entity, component: LocalTransform): void;
    removeLocalTransform(entity: Entity): void;
    hasWorldTransform(entity: Entity): boolean;
    getWorldTransform(entity: Entity): WorldTransform;
    addWorldTransform(entity: Entity, component: WorldTransform): void;
    removeWorldTransform(entity: Entity): void;
    hasVelocity(entity: Entity): boolean;
    getVelocity(entity: Entity): Velocity;
    addVelocity(entity: Entity, component: Velocity): void;
    removeVelocity(entity: Entity): void;
    hasSpineAnimation(entity: Entity): boolean;
    getSpineAnimation(entity: Entity): SpineAnimation;
    addSpineAnimation(entity: Entity, component: SpineAnimation): void;
    removeSpineAnimation(entity: Entity): void;
    hasRigidBody(entity: Entity): boolean;
    getRigidBody(entity: Entity): RigidBody;
    addRigidBody(entity: Entity, component: RigidBody): void;
    removeRigidBody(entity: Entity): void;
    hasBitmapText(entity: Entity): boolean;
    getBitmapText(entity: Entity): BitmapText;
    addBitmapText(entity: Entity, component: BitmapText): void;
    removeBitmapText(entity: Entity): void;
    hasSprite(entity: Entity): boolean;
    getSprite(entity: Entity): Sprite;
    addSprite(entity: Entity, component: Sprite): void;
    removeSprite(entity: Entity): void;
    hasParent(entity: Entity): boolean;
    getParent(entity: Entity): Parent;
    addParent(entity: Entity, component: Parent): void;
    removeParent(entity: Entity): void;
    hasChildren(entity: Entity): boolean;
    getChildren(entity: Entity): Children;
    addChildren(entity: Entity, component: Children): void;
    removeChildren(entity: Entity): void;
    hasCanvas(entity: Entity): boolean;
    getCanvas(entity: Entity): Canvas;
    addCanvas(entity: Entity, component: Canvas): void;
    removeCanvas(entity: Entity): void;
    hasCamera(entity: Entity): boolean;
    getCamera(entity: Entity): Camera;
    addCamera(entity: Entity, component: Camera): void;
    removeCamera(entity: Entity): void;
    setParent(child: Entity, parent: Entity): void;
}

/**
 * @file    wasm.ts
 * @brief   WASM module type definitions
 */

interface CppRegistry extends Registry {
    delete(): void;
    removeParent(entity: Entity): void;
    [key: string]: Function | undefined;
}
interface CppResourceManager {
    createTexture(width: number, height: number, pixels: number, pixelsLen: number, format: number, flipY: boolean): number;
    createShader(vertSrc: string, fragSrc: string): number;
    registerExternalTexture(glTextureId: number, width: number, height: number): number;
    getTextureGLId(handle: number): number;
    releaseTexture(handle: number): void;
    releaseShader(handle: number): void;
    setTextureMetadata(handle: number, left: number, right: number, top: number, bottom: number): void;
    registerTextureWithPath(handle: number, path: string): void;
    loadBitmapFont(fntContent: string, textureHandle: number, texWidth: number, texHeight: number): number;
    createLabelAtlasFont(textureHandle: number, texWidth: number, texHeight: number, chars: string, charWidth: number, charHeight: number): number;
    releaseBitmapFont(handle: number): void;
    measureBitmapText(fontHandle: number, text: string, fontSize: number, spacing: number): {
        width: number;
        height: number;
    };
}
interface EmscriptenFS {
    writeFile(path: string, data: string | Uint8Array): void;
    readFile(path: string, opts?: {
        encoding?: string;
    }): string | Uint8Array;
    mkdir(path: string): void;
    mkdirTree(path: string): void;
    unlink(path: string): void;
    stat(path: string): {
        mode: number;
        size: number;
    };
    isFile(mode: number): boolean;
    isDir(mode: number): boolean;
    analyzePath(path: string): {
        exists: boolean;
        parentExists: boolean;
    };
}
interface SpineBounds {
    x: number;
    y: number;
    width: number;
    height: number;
    valid: boolean;
}
interface ESEngineModule {
    Registry: new () => CppRegistry;
    HEAPU8: Uint8Array;
    HEAPU32: Uint32Array;
    HEAPF32: Float32Array;
    FS: EmscriptenFS;
    materialDataProvider?: (materialId: number, outShaderIdPtr: number, outBlendModePtr: number, outUniformBufferPtr: number, outUniformCountPtr: number) => void;
    initRenderer(): void;
    initRendererWithCanvas(canvasSelector: string): boolean;
    initRendererWithContext(contextHandle: number): boolean;
    shutdownRenderer(): void;
    GL: {
        registerContext(ctx: WebGLRenderingContext | WebGL2RenderingContext, options: {
            majorVersion: number;
            minorVersion: number;
            enableExtensionsByDefault?: boolean;
        }): number;
    };
    renderFrame(registry: CppRegistry, width: number, height: number): void;
    renderFrameWithMatrix(registry: CppRegistry, width: number, height: number, matrixPtr: number): void;
    getResourceManager(): CppResourceManager;
    getSpineBounds?(registry: CppRegistry, entity: number): SpineBounds;
    draw_begin(matrixPtr: number): void;
    draw_end(): void;
    draw_line(fromX: number, fromY: number, toX: number, toY: number, r: number, g: number, b: number, a: number, thickness: number): void;
    draw_rect(x: number, y: number, width: number, height: number, r: number, g: number, b: number, a: number, filled: boolean): void;
    draw_rectOutline(x: number, y: number, width: number, height: number, r: number, g: number, b: number, a: number, thickness: number): void;
    draw_circle(centerX: number, centerY: number, radius: number, r: number, g: number, b: number, a: number, filled: boolean, segments: number): void;
    draw_circleOutline(centerX: number, centerY: number, radius: number, r: number, g: number, b: number, a: number, thickness: number, segments: number): void;
    draw_texture(x: number, y: number, width: number, height: number, textureId: number, r: number, g: number, b: number, a: number): void;
    draw_textureRotated(x: number, y: number, width: number, height: number, rotation: number, textureId: number, r: number, g: number, b: number, a: number): void;
    draw_setLayer(layer: number): void;
    draw_setDepth(depth: number): void;
    draw_getDrawCallCount(): number;
    draw_getPrimitiveCount(): number;
    draw_setBlendMode(mode: number): void;
    draw_setDepthTest(enabled: boolean): void;
    draw_mesh(geometryHandle: number, shaderHandle: number, transformPtr: number): void;
    draw_meshWithUniforms(geometryHandle: number, shaderHandle: number, transformPtr: number, uniformsPtr: number, uniformCount: number): void;
    geometry_create(): number;
    geometry_init(handle: number, verticesPtr: number, vertexCount: number, layoutPtr: number, layoutCount: number, dynamic: boolean): void;
    geometry_setIndices16(handle: number, indicesPtr: number, indexCount: number): void;
    geometry_setIndices32(handle: number, indicesPtr: number, indexCount: number): void;
    geometry_updateVertices(handle: number, verticesPtr: number, vertexCount: number, offset: number): void;
    geometry_release(handle: number): void;
    geometry_isValid(handle: number): boolean;
    postprocess_init(width: number, height: number): boolean;
    postprocess_shutdown(): void;
    postprocess_resize(width: number, height: number): void;
    postprocess_addPass(name: string, shaderHandle: number): number;
    postprocess_removePass(name: string): void;
    postprocess_setPassEnabled(name: string, enabled: boolean): void;
    postprocess_isPassEnabled(name: string): boolean;
    postprocess_setUniformFloat(passName: string, uniform: string, value: number): void;
    postprocess_setUniformVec4(passName: string, uniform: string, x: number, y: number, z: number, w: number): void;
    postprocess_begin(): void;
    postprocess_end(): void;
    postprocess_getPassCount(): number;
    postprocess_isInitialized(): boolean;
    postprocess_setBypass(bypass: boolean): void;
    postprocess_isBypassed(): boolean;
    renderer_init(width: number, height: number): void;
    renderer_resize(width: number, height: number): void;
    renderer_begin(matrixPtr: number, targetHandle: number): void;
    renderer_flush(): void;
    renderer_end(): void;
    renderer_submitSprites(registry: CppRegistry): void;
    renderer_submitBitmapText(registry: CppRegistry): void;
    renderer_submitSpine?(registry: CppRegistry): void;
    renderer_submitTriangles(verticesPtr: number, vertexCount: number, indicesPtr: number, indexCount: number, textureId: number, blendMode: number, transformPtr: number): void;
    renderer_setStage(stage: number): void;
    renderer_createTarget(width: number, height: number, flags: number): number;
    renderer_releaseTarget(handle: number): void;
    renderer_getTargetTexture(handle: number): number;
    renderer_getTargetDepthTexture(handle: number): number;
    renderer_getDrawCalls(): number;
    renderer_getTriangles(): number;
    renderer_getSprites(): number;
    renderer_getText(): number;
    renderer_getSpine?(): number;
    renderer_getMeshes(): number;
    renderer_getCulled(): number;
    renderer_setClearColor(r: number, g: number, b: number, a: number): void;
    renderer_setViewport(x: number, y: number, w: number, h: number): void;
    renderer_setScissor(x: number, y: number, w: number, h: number, enable: boolean): void;
    renderer_clearBuffers(flags: number): void;
    renderer_setEntityClipRect(entity: number, x: number, y: number, w: number, h: number): void;
    renderer_clearEntityClipRect(entity: number): void;
    renderer_clearAllClipRects(): void;
    renderer_clearStencil(): void;
    renderer_setEntityStencilMask(entity: number, refValue: number): void;
    renderer_setEntityStencilTest(entity: number, refValue: number): void;
    renderer_clearEntityStencilMask(entity: number): void;
    renderer_clearAllStencilMasks(): void;
    registry_getCanvasEntity(registry: CppRegistry): number;
    registry_getCameraEntities(registry: CppRegistry): number[];
    getChildEntities(registry: CppRegistry, entity: number): number[];
    gl_enableErrorCheck(enabled: boolean): void;
    gl_checkErrors(context: string): number;
    renderer_diagnose(): void;
    _malloc(size: number): number;
    _free(ptr: number): void;
}

export type { CppRegistry, CppResourceManager, ESEngineModule, EmscriptenFS, SpineBounds };
