name: Bug Report
description: Report a bug in ESEngine
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill in the details below.

  - type: input
    id: version
    attributes:
      label: ESEngine Version
      description: Editor version or SDK version
      placeholder: "e.g., v0.5.0"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of ESEngine is affected?
      options:
        - Editor
        - SDK / Runtime
        - WASM / Renderer
        - Build Pipeline
        - WeChat MiniGame
        - Playable Ads
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Open the editor
        2. Create a new scene
        3. Add a Sprite component
        4. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "e.g., macOS 15.0, Windows 11"

  - type: input
    id: browser
    attributes:
      label: Browser (if applicable)
      placeholder: "e.g., Chrome 120"

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste any relevant error logs or attach screenshots

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might help
