/**
 * @file    esengine.d.ts
 * @brief   ESEngine TypeScript Definitions
 * @details Generated by EHT - DO NOT EDIT
 *
 * @copyright Copyright (c) 2026 ESEngine Team
 */

// Core Types
export type Entity = number;

// Math Types
export interface Vec2 { x: number; y: number; }
export interface Vec3 { x: number; y: number; z: number; }
export interface Vec4 { x: number; y: number; z: number; w: number; }
export interface UVec2 { x: number; y: number; }
export interface Quat { w: number; x: number; y: number; z: number; }
export type Mat4 = number[];

// Enums

export enum ProjectionType {
    Perspective = 0,
    Orthographic = 1,
}

export enum CanvasScaleMode {
    FixedWidth = 0,
    FixedHeight = 1,
    Expand = 2,
    Shrink = 3,
    Match = 4,
}

// Components

export interface Camera {
    projectionType: number;
    fov: number;
    orthoSize: number;
    nearPlane: number;
    farPlane: number;
    aspectRatio: number;
    isActive: boolean;
    priority: number;
}

export interface Canvas {
    designResolution: UVec2;
    pixelsPerUnit: number;
    scaleMode: number;
    matchWidthOrHeight: number;
    backgroundColor: Vec4;
}

export interface Parent {
    entity: number;
}

export interface Children {
}

export interface Sprite {
    texture: number;
    color: Vec4;
    size: Vec2;
    uvOffset: Vec2;
    uvScale: Vec2;
    layer: number;
    flipX: boolean;
    flipY: boolean;
}

export interface LocalTransform {
    position: Vec3;
    rotation: Quat;
    scale: Vec3;
}

export interface WorldTransform {
    position: Vec3;
    rotation: Quat;
    scale: Vec3;
}

export interface Velocity {
    linear: Vec3;
    angular: Vec3;
}

// Registry
export interface Registry {
    create(): Entity;
    destroy(entity: Entity): void;
    valid(entity: Entity): boolean;
    entityCount(): number;

    hasCamera(entity: Entity): boolean;
    getCamera(entity: Entity): Camera;
    addCamera(entity: Entity, component: Camera): void;
    removeCamera(entity: Entity): void;
    hasCanvas(entity: Entity): boolean;
    getCanvas(entity: Entity): Canvas;
    addCanvas(entity: Entity, component: Canvas): void;
    removeCanvas(entity: Entity): void;
    hasParent(entity: Entity): boolean;
    getParent(entity: Entity): Parent;
    addParent(entity: Entity, component: Parent): void;
    removeParent(entity: Entity): void;
    hasChildren(entity: Entity): boolean;
    getChildren(entity: Entity): Children;
    addChildren(entity: Entity, component: Children): void;
    removeChildren(entity: Entity): void;
    hasSprite(entity: Entity): boolean;
    getSprite(entity: Entity): Sprite;
    addSprite(entity: Entity, component: Sprite): void;
    removeSprite(entity: Entity): void;
    hasLocalTransform(entity: Entity): boolean;
    getLocalTransform(entity: Entity): LocalTransform;
    addLocalTransform(entity: Entity, component: LocalTransform): void;
    removeLocalTransform(entity: Entity): void;
    hasWorldTransform(entity: Entity): boolean;
    getWorldTransform(entity: Entity): WorldTransform;
    addWorldTransform(entity: Entity, component: WorldTransform): void;
    removeWorldTransform(entity: Entity): void;
    hasVelocity(entity: Entity): boolean;
    getVelocity(entity: Entity): Velocity;
    addVelocity(entity: Entity, component: Velocity): void;
    removeVelocity(entity: Entity): void;
}

// Resource Manager
export interface ResourceManager {
    createTexture(width: number, height: number, pixelsPtr: number, pixelsLen: number, format: number): number;
    createShader(vertSrc: string, fragSrc: string): number;
    releaseTexture(handleId: number): void;
    releaseShader(handleId: number): void;
    setTextureMetadata(handleId: number, left: number, right: number, top: number, bottom: number): void;
}

// Module
export interface ESEngineModule {
    Registry: new () => Registry;
    Camera: new () => Camera;
    Canvas: new () => Canvas;
    Parent: new () => Parent;
    Children: new () => Children;
    Sprite: new () => Sprite;
    LocalTransform: new () => LocalTransform;
    WorldTransform: new () => WorldTransform;
    Velocity: new () => Velocity;

    // Renderer functions
    initRenderer(): void;
    initRendererWithCanvas(canvasSelector: string): boolean;
    shutdownRenderer(): void;
    renderFrame(registry: Registry, width: number, height: number): void;
    renderFrameWithMatrix(registry: Registry, width: number, height: number, matrixPtr: number): void;
    getResourceManager(): ResourceManager;

    // Memory functions
    _malloc(size: number): number;
    _free(ptr: number): void;
    HEAPU8: Uint8Array;
    HEAPF32: Float32Array;
}

export default function createModule(): Promise<ESEngineModule>;
