async function ESEngineModule(moduleArg={}){var moduleRtn;var g=moduleArg,aa=!!globalThis.window,m=!!globalThis.WorkerGlobalScope,n=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type;if(n){const {createRequire:a}=await import("node:module");var require=a(import.meta.url)}var p=import.meta.url,q="",u,v;
if(n){var fs=require("node:fs");p.startsWith("file:")&&(q=require("node:path").dirname(require("node:url").fileURLToPath(p))+"/");v=a=>{a=w(a)?new URL(a):a;return fs.readFileSync(a)};u=async a=>{a=w(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.slice(2)}else if(aa||m){try{q=(new URL(".",p)).href}catch{}m&&(v=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});u=async a=>{if(w(a))return new Promise((c,d)=>{var e=
new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var x=console.error.bind(console),y,z=!1,w=a=>a.startsWith("file://"),A,B,C,D,E,F,G,H,I,J,K,L,M=!1;
function N(){var a=O.buffer;C=new Int8Array(a);E=new Int16Array(a);g.HEAPU8=D=new Uint8Array(a);F=new Uint16Array(a);G=new Int32Array(a);g.HEAPU32=H=new Uint32Array(a);g.HEAPF32=I=new Float32Array(a);J=new Float64Array(a);K=new BigInt64Array(a);L=new BigUint64Array(a)}var P;async function ba(a){if(!y)try{var b=await u(a);return new Uint8Array(b)}catch{}if(a==P&&y)a=new Uint8Array(y);else if(v)a=v(a);else throw"both async and sync fetching of the wasm failed";return a}
async function ca(a,b){try{var c=await ba(a);return await WebAssembly.instantiate(c,b)}catch(d){throw x(`failed to asynchronously prepare wasm: ${d}`),a=d,g.onAbort?.(a),a="Aborted("+a+")",x(a),z=!0,a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info."),B?.(a),a;}}
async function da(a){var b=P;if(!y&&!w(b)&&!n)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){x(`wasm streaming compile failed: ${d}`),x("falling back to ArrayBuffer instantiation")}return ca(b,a)}
var ea=a=>{for(;0<a.length;)a.shift()(g)},fa=[],ha=[],ia=()=>{var a=g.preRun.shift();ha.push(a)},Q=a=>{for(var b="";;){var c=D[a++];if(!c)return b;b+=String.fromCharCode(c)}},R={},ja={},ka={},S=class extends Error{constructor(a){super(a);this.name="BindingError"}};
function la(a,b,c={}){var d=b.name;if(!a)throw new S(`type "${d}" must have a positive integer typeid pointer`);if(ja.hasOwnProperty(a)){if(c.C)return;throw new S(`Cannot register type '${d}' twice`);}ja[a]=b;delete ka[a];R.hasOwnProperty(a)&&(b=R[a],delete R[a],b.forEach(e=>e()))}function T(a,b,c={}){return la(a,b,c)}
var ma=(a,b,c)=>{switch(b){case 1:return c?d=>C[d]:d=>D[d];case 2:return c?d=>E[d>>1]:d=>F[d>>1];case 4:return c?d=>G[d>>2]:d=>H[d>>2];case 8:return c?d=>K[d>>3]:d=>L[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},oa=[],U=[0,1,,1,null,1,!0,1,!1,1],pa=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=oa.pop()||U.length;U[b]=a;U[b+1]=1;return b}};function V(a){return this.u(H[a>>2])}
var qa={name:"emscripten::val",u:a=>{if(!a)throw new S(`Cannot use deleted val. handle = ${a}`);var b=U[a];9<a&&0===--U[a+1]&&(U[a]=void 0,oa.push(a));return b},A:(a,b)=>pa(b),v:V,B:null},ra=(a,b)=>{switch(b){case 4:return function(c){return this.u(I[c>>2])};case 8:return function(c){return this.u(J[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},sa=(a,b,c)=>{var d=D;if(0<c){c=b+c-1;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);if(127>=f){if(b>=c)break;d[b++]=f}else if(2047>=
f){if(b+1>=c)break;d[b++]=192|f>>6;d[b++]=128|f&63}else if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12;d[b++]=128|f>>6&63;d[b++]=128|f&63}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63;d[b++]=128|f>>6&63;d[b++]=128|f&63;e++}}d[b]=0}},ta=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},ua=globalThis.TextDecoder&&new TextDecoder,va=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},wa=(a=0,b,c)=>{var d=
D;b=va(d,a,b,c);if(16<b-a&&d.buffer&&ua)return ua.decode(d.subarray(a,b));for(c="";a<b;){var e=d[a++];if(e&128){var f=d[a++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var h=d[a++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|d[a++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},xa=globalThis.TextDecoder?new TextDecoder("utf-16le"):void 0,ya=(a,b,c)=>{a>>=1;b=va(F,a,b/2,c);if(16<
b-a&&xa)return xa.decode(F.subarray(a,b));for(c="";a<b;++a)c+=String.fromCharCode(F[a]);return c},za=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)E[b>>1]=a.charCodeAt(e),b+=2;E[b>>1]=0;return b-d},Aa=a=>2*a.length,Ba=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=H[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},Ca=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);
65535<f&&e++;G[b>>2]=f;b+=4;if(b+4>c)break}G[b>>2]=0;return b-d},Da=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},Ga=(a,b,c,d)=>{var e={string:l=>{var r=0;if(null!==l&&void 0!==l&&0!==l){r=ta(l)+1;var na=W(r);sa(l,na,r);r=na}return r},array:l=>{var r=W(l.length);C.set(l,r);return r}};a=g["_"+a];var f=[],h=0;if(d)for(var k=0;k<d.length;k++){var t=e[c[k]];t?(0===h&&(h=Ea()),f[k]=t(d[k])):f[k]=d[k]}c=a(...f);return c=function(l){0!==h&&Fa(h);return"string"===b?l?wa(l):
"":"boolean"===b?!!l:l}(c)};g.printErr&&(x=g.printErr);g.wasmBinary&&(y=g.wasmBinary);if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.shift()();g.ccall=Ga;g.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?g["_"+a]:(...f)=>Ga(a,b,c,f,d)};
var X,Y,Fa,W,Ea,O,Ha={e:(a,b,c,d,e)=>{b=Q(b);d=0n===d;let f=h=>h;if(d){const h=8*c;f=k=>BigInt.asUintN(h,k);e=f(e)}T(a,{name:b,u:f,A:(h,k)=>{"number"==typeof k&&(k=BigInt(k));return k},v:ma(b,c,!d),B:null})},h:(a,b,c,d)=>{b=Q(b);T(a,{name:b,u:function(e){return!!e},A:function(e,f){return f?c:d},v:function(e){return this.u(D[e])},B:null})},f:a=>T(a,qa),d:(a,b,c)=>{b=Q(b);T(a,{name:b,u:d=>d,A:(d,e)=>e,v:ra(b,c),B:null})},b:(a,b,c,d,e)=>{b=Q(b);let f=k=>k;if(0===d){var h=32-8*c;f=k=>k<<h>>>h;e=f(e)}T(a,
{name:b,u:f,A:(k,t)=>t,v:ma(b,c,0!==d),B:null})},a:(a,b,c)=>{function d(f){return new e(C.buffer,H[f+4>>2],H[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=Q(c);T(a,{name:c,u:d,v:d},{C:!0})},g:(a,b)=>{b=Q(b);T(a,{name:b,u(c){var d=(d=c+4)?wa(d,H[c>>2],!0):"";Y(c);return d},A(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new S("Cannot pass non-string to std::string");
var f=e?ta(d):d.length;var h=X(4+f+1),k=h+4;H[h>>2]=f;e?sa(d,k,f+1):D.set(d,k);null!==c&&c.push(Y,h);return h},v:V,B(c){Y(c)}})},c:(a,b,c)=>{c=Q(c);if(2===b){var d=ya;var e=za;var f=Aa}else d=Ba,e=Ca,f=Da;T(a,{name:c,u:h=>{var k=d(h+4,H[h>>2]*b,!0);Y(h);return k},A:(h,k)=>{if("string"!=typeof k)throw new S(`Cannot pass non-string to C++ string type ${c}`);var t=f(k),l=X(4+t+b);H[l>>2]=t/b;e(k,l+4,t+b);null!==h&&h.push(Y,l);return l},v:V,B(h){Y(h)}})},i:(a,b)=>{b=Q(b);T(a,{D:!0,name:b,u:()=>{},A:()=>
{}})},j:a=>{var b=D.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-O.buffer.byteLength+65535)/65536|0;try{O.grow(d);N();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1}},Z;
Z=await (async function(){function a(c){c=Z=c.exports;g._es_sdk_init=c.m;g._es_sdk_version=c.n;X=g._malloc=c.o;Y=g._free=c.p;Fa=c.q;W=c.r;Ea=c.s;O=c.k;N();return Z}var b={a:Ha};if(g.instantiateWasm)return new Promise(c=>{g.instantiateWasm(b,(d,e)=>{c(a(d,e))})});P??=g.locateFile?g.locateFile?g.locateFile("esengine.wasm",q):q+"esengine.wasm":(new URL("esengine.wasm",import.meta.url)).href;return a((await da(b)).instance)}());
(function(){function a(){g.calledRun=!0;if(!z){M=!0;Z.l();A?.(g);g.onRuntimeInitialized?.();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();fa.push(b)}ea(fa)}}if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)ia();ea(ha);g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);a()},1)):a()})();M?moduleRtn=g:moduleRtn=new Promise((a,b)=>{A=a;B=b});
;return moduleRtn}export default ESEngineModule;
