/**
 * @file    wasm.generated.ts
 * @brief   ESEngine WASM Bindings TypeScript Definitions
 * @details Generated by EHT - DO NOT EDIT
 */

import type { Entity, Vec2, Vec3, Vec4, Quat } from './types';

// Additional Math Types
export interface UVec2 { x: number; y: number; }
export type Mat4 = number[];

// Emscripten Vector Types
export interface VectorEntity {
    size(): number;
    get(index: number): number;
    push_back(value: number): void;
    set(index: number, value: number): boolean;
    delete(): void;
}

// Enums

export enum EmitterShape {
    Point = 0,
    Circle = 1,
    Rectangle = 2,
    Cone = 3,
}

export enum SimulationSpace {
    World = 0,
    Local = 1,
}

export enum BodyType {
    Static = 0,
    Kinematic = 1,
    Dynamic = 2,
}

export enum TextAlign {
    Left = 0,
    Center = 1,
    Right = 2,
}

export enum MaskMode {
    Scissor = 0,
    Stencil = 1,
}

export enum FlexDirection {
    Row = 0,
    Column = 1,
    RowReverse = 2,
    ColumnReverse = 3,
}

export enum FlexWrap {
    NoWrap = 0,
    Wrap = 1,
}

export enum JustifyContent {
    Start = 0,
    Center = 1,
    End = 2,
    SpaceBetween = 3,
    SpaceAround = 4,
    SpaceEvenly = 5,
}

export enum AlignItems {
    Start = 0,
    Center = 1,
    End = 2,
    Stretch = 3,
}

export enum CanvasScaleMode {
    FixedWidth = 0,
    FixedHeight = 1,
    Expand = 2,
    Shrink = 3,
    Match = 4,
}

export enum ProjectionType {
    Perspective = 0,
    Orthographic = 1,
}

// Components

export interface UIRect {
    anchorMin: Vec2;
    anchorMax: Vec2;
    offsetMin: Vec2;
    offsetMax: Vec2;
    size: Vec2;
    pivot: Vec2;
}

export interface FlexItem {
    flexGrow: number;
    flexShrink: number;
    flexBasis: number;
    order: number;
}

export interface BoxCollider {
    halfExtents: Vec2;
    offset: Vec2;
    density: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
    enabled: boolean;
}

export interface CircleCollider {
    radius: number;
    offset: Vec2;
    density: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
    enabled: boolean;
}

export interface CapsuleCollider {
    radius: number;
    halfHeight: number;
    offset: Vec2;
    density: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
    enabled: boolean;
}

export interface ParticleEmitter {
    rate: number;
    burstCount: number;
    burstInterval: number;
    duration: number;
    looping: boolean;
    playOnStart: boolean;
    maxParticles: number;
    lifetimeMin: number;
    lifetimeMax: number;
    shape: number;
    shapeRadius: number;
    shapeSize: Vec2;
    shapeAngle: number;
    speedMin: number;
    speedMax: number;
    angleSpreadMin: number;
    angleSpreadMax: number;
    startSizeMin: number;
    startSizeMax: number;
    endSizeMin: number;
    endSizeMax: number;
    sizeEasing: number;
    startColor: Vec4;
    endColor: Vec4;
    colorEasing: number;
    rotationMin: number;
    rotationMax: number;
    angularVelocityMin: number;
    angularVelocityMax: number;
    gravity: Vec2;
    damping: number;
    texture: number;
    spriteColumns: number;
    spriteRows: number;
    spriteFPS: number;
    spriteLoop: boolean;
    blendMode: number;
    layer: number;
    material: number;
    simulationSpace: number;
    enabled: boolean;
}

export interface Transform {
    position: Vec3;
    rotation: Quat;
    scale: Vec3;
    worldPosition: Vec3;
    worldRotation: Quat;
    worldScale: Vec3;
}

export interface Velocity {
    linear: Vec3;
    angular: Vec3;
}

export interface SpineAnimation {
    skeletonPath: string;
    atlasPath: string;
    skin: string;
    animation: string;
    timeScale: number;
    loop: boolean;
    playing: boolean;
    flipX: boolean;
    flipY: boolean;
    color: Vec4;
    layer: number;
    skeletonScale: number;
    material: number;
    enabled: boolean;
}

export interface Interactable {
    enabled: boolean;
    blockRaycast: boolean;
    raycastTarget: boolean;
}

export interface UIInteraction {
    hovered: boolean;
    pressed: boolean;
    justPressed: boolean;
    justReleased: boolean;
}

export interface RigidBody {
    bodyType: number;
    gravityScale: number;
    linearDamping: number;
    angularDamping: number;
    fixedRotation: boolean;
    bullet: boolean;
    enabled: boolean;
}

export interface BitmapText {
    text: string;
    color: Vec4;
    fontSize: number;
    align: number;
    spacing: number;
    layer: number;
    font: number;
    enabled: boolean;
}

export interface Sprite {
    texture: number;
    color: Vec4;
    size: Vec2;
    uvOffset: Vec2;
    uvScale: Vec2;
    layer: number;
    flipX: boolean;
    flipY: boolean;
    material: number;
    enabled: boolean;
}

export interface UIMask {
    enabled: boolean;
    mode: number;
}

export interface FlexContainer {
    direction: number;
    wrap: number;
    justifyContent: number;
    alignItems: number;
    gap: Vec2;
    padding: Vec4;
}

export interface Parent {
    entity: number;
}

export interface Children {
    entities: VectorEntity;
}

export interface ScreenSpace {
}

export interface Canvas {
    designResolution: UVec2;
    pixelsPerUnit: number;
    scaleMode: number;
    matchWidthOrHeight: number;
    backgroundColor: Vec4;
}

export interface Camera {
    projectionType: number;
    fov: number;
    orthoSize: number;
    nearPlane: number;
    farPlane: number;
    aspectRatio: number;
    isActive: boolean;
    priority: number;
    viewportX: number;
    viewportY: number;
    viewportW: number;
    viewportH: number;
    clearFlags: number;
}

// Registry
export interface Registry {
    create(): Entity;
    destroy(entity: Entity): void;
    valid(entity: Entity): boolean;
    entityCount(): number;

    hasUIRect(entity: Entity): boolean;
    getUIRect(entity: Entity): UIRect;
    addUIRect(entity: Entity, component: UIRect): void;
    removeUIRect(entity: Entity): void;
    hasFlexItem(entity: Entity): boolean;
    getFlexItem(entity: Entity): FlexItem;
    addFlexItem(entity: Entity, component: FlexItem): void;
    removeFlexItem(entity: Entity): void;
    hasBoxCollider(entity: Entity): boolean;
    getBoxCollider(entity: Entity): BoxCollider;
    addBoxCollider(entity: Entity, component: BoxCollider): void;
    removeBoxCollider(entity: Entity): void;
    hasCircleCollider(entity: Entity): boolean;
    getCircleCollider(entity: Entity): CircleCollider;
    addCircleCollider(entity: Entity, component: CircleCollider): void;
    removeCircleCollider(entity: Entity): void;
    hasCapsuleCollider(entity: Entity): boolean;
    getCapsuleCollider(entity: Entity): CapsuleCollider;
    addCapsuleCollider(entity: Entity, component: CapsuleCollider): void;
    removeCapsuleCollider(entity: Entity): void;
    hasParticleEmitter(entity: Entity): boolean;
    getParticleEmitter(entity: Entity): ParticleEmitter;
    addParticleEmitter(entity: Entity, component: ParticleEmitter): void;
    removeParticleEmitter(entity: Entity): void;
    hasTransform(entity: Entity): boolean;
    getTransform(entity: Entity): Transform;
    addTransform(entity: Entity, component: Transform): void;
    removeTransform(entity: Entity): void;
    hasVelocity(entity: Entity): boolean;
    getVelocity(entity: Entity): Velocity;
    addVelocity(entity: Entity, component: Velocity): void;
    removeVelocity(entity: Entity): void;
    hasSpineAnimation(entity: Entity): boolean;
    getSpineAnimation(entity: Entity): SpineAnimation;
    addSpineAnimation(entity: Entity, component: SpineAnimation): void;
    removeSpineAnimation(entity: Entity): void;
    hasInteractable(entity: Entity): boolean;
    getInteractable(entity: Entity): Interactable;
    addInteractable(entity: Entity, component: Interactable): void;
    removeInteractable(entity: Entity): void;
    hasUIInteraction(entity: Entity): boolean;
    getUIInteraction(entity: Entity): UIInteraction;
    addUIInteraction(entity: Entity, component: UIInteraction): void;
    removeUIInteraction(entity: Entity): void;
    hasRigidBody(entity: Entity): boolean;
    getRigidBody(entity: Entity): RigidBody;
    addRigidBody(entity: Entity, component: RigidBody): void;
    removeRigidBody(entity: Entity): void;
    hasBitmapText(entity: Entity): boolean;
    getBitmapText(entity: Entity): BitmapText;
    addBitmapText(entity: Entity, component: BitmapText): void;
    removeBitmapText(entity: Entity): void;
    hasSprite(entity: Entity): boolean;
    getSprite(entity: Entity): Sprite;
    addSprite(entity: Entity, component: Sprite): void;
    removeSprite(entity: Entity): void;
    hasUIMask(entity: Entity): boolean;
    getUIMask(entity: Entity): UIMask;
    addUIMask(entity: Entity, component: UIMask): void;
    removeUIMask(entity: Entity): void;
    hasFlexContainer(entity: Entity): boolean;
    getFlexContainer(entity: Entity): FlexContainer;
    addFlexContainer(entity: Entity, component: FlexContainer): void;
    removeFlexContainer(entity: Entity): void;
    hasParent(entity: Entity): boolean;
    getParent(entity: Entity): Parent;
    addParent(entity: Entity, component: Parent): void;
    removeParent(entity: Entity): void;
    hasChildren(entity: Entity): boolean;
    getChildren(entity: Entity): Children;
    addChildren(entity: Entity, component: Children): void;
    removeChildren(entity: Entity): void;
    hasScreenSpace(entity: Entity): boolean;
    getScreenSpace(entity: Entity): ScreenSpace;
    addScreenSpace(entity: Entity, component: ScreenSpace): void;
    removeScreenSpace(entity: Entity): void;
    hasCanvas(entity: Entity): boolean;
    getCanvas(entity: Entity): Canvas;
    addCanvas(entity: Entity, component: Canvas): void;
    removeCanvas(entity: Entity): void;
    hasCamera(entity: Entity): boolean;
    getCamera(entity: Entity): Camera;
    addCamera(entity: Entity, component: Camera): void;
    removeCamera(entity: Entity): void;

    // Hierarchy Utilities
    setParent(child: Entity, parent: Entity): void;
}

// Module
export interface ESEngineModule {
    Registry: new () => Registry;
    UIRect: new () => UIRect;
    FlexItem: new () => FlexItem;
    BoxCollider: new () => BoxCollider;
    CircleCollider: new () => CircleCollider;
    CapsuleCollider: new () => CapsuleCollider;
    ParticleEmitter: new () => ParticleEmitter;
    Transform: new () => Transform;
    Velocity: new () => Velocity;
    SpineAnimation: new () => SpineAnimation;
    Interactable: new () => Interactable;
    UIInteraction: new () => UIInteraction;
    RigidBody: new () => RigidBody;
    BitmapText: new () => BitmapText;
    Sprite: new () => Sprite;
    UIMask: new () => UIMask;
    FlexContainer: new () => FlexContainer;
    Parent: new () => Parent;
    Children: new () => Children;
    ScreenSpace: new () => ScreenSpace;
    Canvas: new () => Canvas;
    Camera: new () => Camera;
}
