/**
 * @file    wasm.generated.ts
 * @brief   ESEngine WASM Bindings TypeScript Definitions
 * @details Generated by EHT - DO NOT EDIT
 */

import type { Entity, Vec2, Vec3, Vec4, Color, Quat } from './types';

// Additional Math Types
export interface UVec2 { x: number; y: number; }
export type Mat4 = number[];

// Enums

export enum BodyType {
    Static = 0,
    Kinematic = 1,
    Dynamic = 2,
}

export enum CanvasScaleMode {
    FixedWidth = 0,
    FixedHeight = 1,
    Expand = 2,
    Shrink = 3,
    Match = 4,
}

export enum ProjectionType {
    Perspective = 0,
    Orthographic = 1,
}

// Components

export interface BoxCollider {
    halfExtents: Vec2;
    offset: Vec2;
    density: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
}

export interface CircleCollider {
    radius: number;
    offset: Vec2;
    density: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
}

export interface CapsuleCollider {
    radius: number;
    halfHeight: number;
    offset: Vec2;
    density: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
}

export interface LocalTransform {
    position: Vec3;
    rotation: Quat;
    scale: Vec3;
}

export interface WorldTransform {
    position: Vec3;
    rotation: Quat;
    scale: Vec3;
}

export interface Velocity {
    linear: Vec3;
    angular: Vec3;
}

export interface SpineAnimation {
    skeletonPath: string;
    atlasPath: string;
    skin: string;
    animation: string;
    timeScale: number;
    loop: boolean;
    playing: boolean;
    flipX: boolean;
    flipY: boolean;
    color: Color;
    layer: number;
    skeletonScale: number;
    material: number;
}

export interface RigidBody {
    bodyType: number;
    gravityScale: number;
    linearDamping: number;
    angularDamping: number;
    fixedRotation: boolean;
    bullet: boolean;
    enabled: boolean;
}

export interface Sprite {
    texture: number;
    color: Color;
    size: Vec2;
    uvOffset: Vec2;
    uvScale: Vec2;
    layer: number;
    flipX: boolean;
    flipY: boolean;
    material: number;
}

export interface Parent {
    entity: number;
}

export interface Children {
}

export interface Canvas {
    designResolution: UVec2;
    pixelsPerUnit: number;
    scaleMode: number;
    matchWidthOrHeight: number;
    backgroundColor: Color;
}

export interface Camera {
    projectionType: number;
    fov: number;
    orthoSize: number;
    nearPlane: number;
    farPlane: number;
    aspectRatio: number;
    isActive: boolean;
    priority: number;
}

// Registry
export interface Registry {
    create(): Entity;
    destroy(entity: Entity): void;
    valid(entity: Entity): boolean;
    entityCount(): number;

    hasBoxCollider(entity: Entity): boolean;
    getBoxCollider(entity: Entity): BoxCollider;
    addBoxCollider(entity: Entity, component: BoxCollider): void;
    removeBoxCollider(entity: Entity): void;
    hasCircleCollider(entity: Entity): boolean;
    getCircleCollider(entity: Entity): CircleCollider;
    addCircleCollider(entity: Entity, component: CircleCollider): void;
    removeCircleCollider(entity: Entity): void;
    hasCapsuleCollider(entity: Entity): boolean;
    getCapsuleCollider(entity: Entity): CapsuleCollider;
    addCapsuleCollider(entity: Entity, component: CapsuleCollider): void;
    removeCapsuleCollider(entity: Entity): void;
    hasLocalTransform(entity: Entity): boolean;
    getLocalTransform(entity: Entity): LocalTransform;
    addLocalTransform(entity: Entity, component: LocalTransform): void;
    removeLocalTransform(entity: Entity): void;
    hasWorldTransform(entity: Entity): boolean;
    getWorldTransform(entity: Entity): WorldTransform;
    addWorldTransform(entity: Entity, component: WorldTransform): void;
    removeWorldTransform(entity: Entity): void;
    hasVelocity(entity: Entity): boolean;
    getVelocity(entity: Entity): Velocity;
    addVelocity(entity: Entity, component: Velocity): void;
    removeVelocity(entity: Entity): void;
    hasSpineAnimation(entity: Entity): boolean;
    getSpineAnimation(entity: Entity): SpineAnimation;
    addSpineAnimation(entity: Entity, component: SpineAnimation): void;
    removeSpineAnimation(entity: Entity): void;
    hasRigidBody(entity: Entity): boolean;
    getRigidBody(entity: Entity): RigidBody;
    addRigidBody(entity: Entity, component: RigidBody): void;
    removeRigidBody(entity: Entity): void;
    hasSprite(entity: Entity): boolean;
    getSprite(entity: Entity): Sprite;
    addSprite(entity: Entity, component: Sprite): void;
    removeSprite(entity: Entity): void;
    hasParent(entity: Entity): boolean;
    getParent(entity: Entity): Parent;
    addParent(entity: Entity, component: Parent): void;
    removeParent(entity: Entity): void;
    hasChildren(entity: Entity): boolean;
    getChildren(entity: Entity): Children;
    addChildren(entity: Entity, component: Children): void;
    removeChildren(entity: Entity): void;
    hasCanvas(entity: Entity): boolean;
    getCanvas(entity: Entity): Canvas;
    addCanvas(entity: Entity, component: Canvas): void;
    removeCanvas(entity: Entity): void;
    hasCamera(entity: Entity): boolean;
    getCamera(entity: Entity): Camera;
    addCamera(entity: Entity, component: Camera): void;
    removeCamera(entity: Entity): void;

    // Hierarchy Utilities
    setParent(child: Entity, parent: Entity): void;
}

// Module
export interface ESEngineModule {
    Registry: new () => Registry;
    BoxCollider: new () => BoxCollider;
    CircleCollider: new () => CircleCollider;
    CapsuleCollider: new () => CapsuleCollider;
    LocalTransform: new () => LocalTransform;
    WorldTransform: new () => WorldTransform;
    Velocity: new () => Velocity;
    SpineAnimation: new () => SpineAnimation;
    RigidBody: new () => RigidBody;
    Sprite: new () => Sprite;
    Parent: new () => Parent;
    Children: new () => Children;
    Canvas: new () => Canvas;
    Camera: new () => Camera;
}
