/**
 * @file    types.ts
 * @brief   Core type definitions for ESEngine SDK
 */
type Entity = number;
declare const INVALID_ENTITY: Entity;
type TextureHandle = number;
declare const INVALID_TEXTURE: TextureHandle;
type FontHandle = number;
declare const INVALID_FONT: FontHandle;
declare const INVALID_MATERIAL = 0;
interface Vec2 {
    x: number;
    y: number;
}
interface Vec3 {
    x: number;
    y: number;
    z: number;
}
interface Vec4 {
    x: number;
    y: number;
    z: number;
    w: number;
}
interface Quat {
    w: number;
    x: number;
    y: number;
    z: number;
}
interface Color {
    r: number;
    g: number;
    b: number;
    a: number;
}
declare const vec2: (x?: number, y?: number) => Vec2;
declare const vec3: (x?: number, y?: number, z?: number) => Vec3;
declare const vec4: (x?: number, y?: number, z?: number, w?: number) => Vec4;
declare const color: (r?: number, g?: number, b?: number, a?: number) => Color;
declare const quat: (w?: number, x?: number, y?: number, z?: number) => Quat;

/**
 * @file    wasm.generated.ts
 * @brief   ESEngine WASM Bindings TypeScript Definitions
 * @details Generated by EHT - DO NOT EDIT
 */

interface UVec2 {
    x: number;
    y: number;
}
interface Padding {
    left: number;
    top: number;
    right: number;
    bottom: number;
}
interface VectorEntity {
    size(): number;
    get(index: number): number;
    push_back(value: number): void;
    set(index: number, value: number): boolean;
    delete(): void;
}
interface UIRect {
    anchorMin: Vec2;
    anchorMax: Vec2;
    offsetMin: Vec2;
    offsetMax: Vec2;
    size: Vec2;
    pivot: Vec2;
}
interface FlexItem {
    flexGrow: number;
    flexShrink: number;
    flexBasis: number;
    order: number;
}
interface BoxCollider {
    halfExtents: Vec2;
    offset: Vec2;
    density: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
    enabled: boolean;
    categoryBits: number;
    maskBits: number;
}
interface CircleCollider {
    radius: number;
    offset: Vec2;
    density: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
    enabled: boolean;
    categoryBits: number;
    maskBits: number;
}
interface CapsuleCollider {
    radius: number;
    halfHeight: number;
    offset: Vec2;
    density: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
    enabled: boolean;
    categoryBits: number;
    maskBits: number;
}
interface SegmentCollider {
    point1: Vec2;
    point2: Vec2;
    density: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
    enabled: boolean;
    categoryBits: number;
    maskBits: number;
}
interface ParticleEmitter {
    rate: number;
    burstCount: number;
    burstInterval: number;
    duration: number;
    looping: boolean;
    playOnStart: boolean;
    maxParticles: number;
    lifetimeMin: number;
    lifetimeMax: number;
    shape: number;
    shapeRadius: number;
    shapeSize: Vec2;
    shapeAngle: number;
    speedMin: number;
    speedMax: number;
    angleSpreadMin: number;
    angleSpreadMax: number;
    startSizeMin: number;
    startSizeMax: number;
    endSizeMin: number;
    endSizeMax: number;
    sizeEasing: number;
    startColor: Vec4;
    endColor: Vec4;
    colorEasing: number;
    rotationMin: number;
    rotationMax: number;
    angularVelocityMin: number;
    angularVelocityMax: number;
    gravity: Vec2;
    damping: number;
    texture: number;
    spriteColumns: number;
    spriteRows: number;
    spriteFPS: number;
    spriteLoop: boolean;
    blendMode: number;
    layer: number;
    material: number;
    simulationSpace: number;
    enabled: boolean;
}
interface Transform {
    position: Vec3;
    rotation: Quat;
    scale: Vec3;
    worldPosition: Vec3;
    worldRotation: Quat;
    worldScale: Vec3;
}
interface UIRenderer {
    visualType: number;
    texture: number;
    color: Vec4;
    uvOffset: Vec2;
    uvScale: Vec2;
    sliceBorder: Vec4;
    material: number;
    enabled: boolean;
}
interface Velocity {
    linear: Vec3;
    angular: Vec3;
}
interface SpineAnimation {
    skeletonPath: string;
    atlasPath: string;
    skin: string;
    animation: string;
    timeScale: number;
    loop: boolean;
    playing: boolean;
    flipX: boolean;
    flipY: boolean;
    color: Vec4;
    layer: number;
    skeletonScale: number;
    material: number;
    enabled: boolean;
}
interface Interactable {
    enabled: boolean;
    blockRaycast: boolean;
    raycastTarget: boolean;
}
interface UIInteraction {
    hovered: boolean;
    pressed: boolean;
    justPressed: boolean;
    justReleased: boolean;
}
interface RigidBody {
    bodyType: number;
    gravityScale: number;
    linearDamping: number;
    angularDamping: number;
    fixedRotation: boolean;
    bullet: boolean;
    enabled: boolean;
}
interface BitmapText {
    text: string;
    color: Vec4;
    fontSize: number;
    align: number;
    spacing: number;
    layer: number;
    font: number;
    enabled: boolean;
}
interface Sprite {
    texture: number;
    color: Vec4;
    size: Vec2;
    pivot: Vec2;
    uvOffset: Vec2;
    uvScale: Vec2;
    layer: number;
    flipX: boolean;
    flipY: boolean;
    material: number;
    enabled: boolean;
}
interface UIMask {
    enabled: boolean;
    mode: number;
}
interface FlexContainer {
    direction: number;
    wrap: number;
    justifyContent: number;
    alignItems: number;
    gap: Vec2;
    padding: Padding;
}
interface Parent {
    entity: number;
}
interface Children {
    entities: VectorEntity;
}
interface ShapeRenderer {
    shapeType: number;
    color: Vec4;
    size: Vec2;
    cornerRadius: number;
    layer: number;
    enabled: boolean;
}
interface LayoutGroup {
    direction: number;
    spacing: number;
    padding: Padding;
    childAlignment: number;
    reverseOrder: boolean;
}
interface ScreenSpace {
}
interface Canvas {
    designResolution: UVec2;
    pixelsPerUnit: number;
    scaleMode: number;
    matchWidthOrHeight: number;
    backgroundColor: Vec4;
}
interface Camera {
    projectionType: number;
    fov: number;
    orthoSize: number;
    nearPlane: number;
    farPlane: number;
    aspectRatio: number;
    isActive: boolean;
    priority: number;
    viewportX: number;
    viewportY: number;
    viewportW: number;
    viewportH: number;
    clearFlags: number;
}
interface Registry {
    create(): Entity;
    destroy(entity: Entity): void;
    valid(entity: Entity): boolean;
    entityCount(): number;
    hasUIRect(entity: Entity): boolean;
    getUIRect(entity: Entity): UIRect;
    addUIRect(entity: Entity, component: UIRect): void;
    removeUIRect(entity: Entity): void;
    hasFlexItem(entity: Entity): boolean;
    getFlexItem(entity: Entity): FlexItem;
    addFlexItem(entity: Entity, component: FlexItem): void;
    removeFlexItem(entity: Entity): void;
    hasBoxCollider(entity: Entity): boolean;
    getBoxCollider(entity: Entity): BoxCollider;
    addBoxCollider(entity: Entity, component: BoxCollider): void;
    removeBoxCollider(entity: Entity): void;
    hasCircleCollider(entity: Entity): boolean;
    getCircleCollider(entity: Entity): CircleCollider;
    addCircleCollider(entity: Entity, component: CircleCollider): void;
    removeCircleCollider(entity: Entity): void;
    hasCapsuleCollider(entity: Entity): boolean;
    getCapsuleCollider(entity: Entity): CapsuleCollider;
    addCapsuleCollider(entity: Entity, component: CapsuleCollider): void;
    removeCapsuleCollider(entity: Entity): void;
    hasSegmentCollider(entity: Entity): boolean;
    getSegmentCollider(entity: Entity): SegmentCollider;
    addSegmentCollider(entity: Entity, component: SegmentCollider): void;
    removeSegmentCollider(entity: Entity): void;
    hasParticleEmitter(entity: Entity): boolean;
    getParticleEmitter(entity: Entity): ParticleEmitter;
    addParticleEmitter(entity: Entity, component: ParticleEmitter): void;
    removeParticleEmitter(entity: Entity): void;
    hasTransform(entity: Entity): boolean;
    getTransform(entity: Entity): Transform;
    addTransform(entity: Entity, component: Transform): void;
    removeTransform(entity: Entity): void;
    hasUIRenderer(entity: Entity): boolean;
    getUIRenderer(entity: Entity): UIRenderer;
    addUIRenderer(entity: Entity, component: UIRenderer): void;
    removeUIRenderer(entity: Entity): void;
    hasVelocity(entity: Entity): boolean;
    getVelocity(entity: Entity): Velocity;
    addVelocity(entity: Entity, component: Velocity): void;
    removeVelocity(entity: Entity): void;
    hasSpineAnimation(entity: Entity): boolean;
    getSpineAnimation(entity: Entity): SpineAnimation;
    addSpineAnimation(entity: Entity, component: SpineAnimation): void;
    removeSpineAnimation(entity: Entity): void;
    hasInteractable(entity: Entity): boolean;
    getInteractable(entity: Entity): Interactable;
    addInteractable(entity: Entity, component: Interactable): void;
    removeInteractable(entity: Entity): void;
    hasUIInteraction(entity: Entity): boolean;
    getUIInteraction(entity: Entity): UIInteraction;
    addUIInteraction(entity: Entity, component: UIInteraction): void;
    removeUIInteraction(entity: Entity): void;
    hasRigidBody(entity: Entity): boolean;
    getRigidBody(entity: Entity): RigidBody;
    addRigidBody(entity: Entity, component: RigidBody): void;
    removeRigidBody(entity: Entity): void;
    hasBitmapText(entity: Entity): boolean;
    getBitmapText(entity: Entity): BitmapText;
    addBitmapText(entity: Entity, component: BitmapText): void;
    removeBitmapText(entity: Entity): void;
    hasSprite(entity: Entity): boolean;
    getSprite(entity: Entity): Sprite;
    addSprite(entity: Entity, component: Sprite): void;
    removeSprite(entity: Entity): void;
    hasUIMask(entity: Entity): boolean;
    getUIMask(entity: Entity): UIMask;
    addUIMask(entity: Entity, component: UIMask): void;
    removeUIMask(entity: Entity): void;
    hasFlexContainer(entity: Entity): boolean;
    getFlexContainer(entity: Entity): FlexContainer;
    addFlexContainer(entity: Entity, component: FlexContainer): void;
    removeFlexContainer(entity: Entity): void;
    hasParent(entity: Entity): boolean;
    getParent(entity: Entity): Parent;
    addParent(entity: Entity, component: Parent): void;
    removeParent(entity: Entity): void;
    hasChildren(entity: Entity): boolean;
    getChildren(entity: Entity): Children;
    addChildren(entity: Entity, component: Children): void;
    removeChildren(entity: Entity): void;
    hasShapeRenderer(entity: Entity): boolean;
    getShapeRenderer(entity: Entity): ShapeRenderer;
    addShapeRenderer(entity: Entity, component: ShapeRenderer): void;
    removeShapeRenderer(entity: Entity): void;
    hasLayoutGroup(entity: Entity): boolean;
    getLayoutGroup(entity: Entity): LayoutGroup;
    addLayoutGroup(entity: Entity, component: LayoutGroup): void;
    removeLayoutGroup(entity: Entity): void;
    hasScreenSpace(entity: Entity): boolean;
    getScreenSpace(entity: Entity): ScreenSpace;
    addScreenSpace(entity: Entity, component: ScreenSpace): void;
    removeScreenSpace(entity: Entity): void;
    hasCanvas(entity: Entity): boolean;
    getCanvas(entity: Entity): Canvas;
    addCanvas(entity: Entity, component: Canvas): void;
    removeCanvas(entity: Entity): void;
    hasCamera(entity: Entity): boolean;
    getCamera(entity: Entity): Camera;
    addCamera(entity: Entity, component: Camera): void;
    removeCamera(entity: Entity): void;
    setParent(child: Entity, parent: Entity): void;
}

/**
 * @file    wasm.ts
 * @brief   WASM module type definitions
 */

interface CppRegistry extends Registry {
    delete(): void;
    removeParent(entity: Entity): void;
    [key: string]: Function | undefined;
}
interface CppResourceManager {
    createTexture(width: number, height: number, pixels: number, pixelsLen: number, format: number, flipY: boolean): number;
    createTextureEx(width: number, height: number, pixels: number, pixelsLen: number, format: number, flipY: boolean, filterMode: number, wrapMode: number): number;
    createShader(vertSrc: string, fragSrc: string): number;
    registerExternalTexture(glTextureId: number, width: number, height: number): number;
    getTextureGLId(handle: number): number;
    releaseTexture(handle: number): void;
    releaseShader(handle: number): void;
    setTextureMetadata(handle: number, left: number, right: number, top: number, bottom: number): void;
    registerTextureWithPath(handle: number, path: string): void;
    loadBitmapFont(fntContent: string, textureHandle: number, texWidth: number, texHeight: number): number;
    createLabelAtlasFont(textureHandle: number, texWidth: number, texHeight: number, chars: string, charWidth: number, charHeight: number): number;
    releaseBitmapFont(handle: number): void;
    measureBitmapText(fontHandle: number, text: string, fontSize: number, spacing: number): {
        width: number;
        height: number;
    };
}
interface EmscriptenFS {
    writeFile(path: string, data: string | Uint8Array): void;
    readFile(path: string, opts?: {
        encoding?: string;
    }): string | Uint8Array;
    mkdir(path: string): void;
    mkdirTree(path: string): void;
    unlink(path: string): void;
    stat(path: string): {
        mode: number;
        size: number;
    };
    isFile(mode: number): boolean;
    isDir(mode: number): boolean;
    analyzePath(path: string): {
        exists: boolean;
        parentExists: boolean;
    };
}
interface SpineBounds {
    x: number;
    y: number;
    width: number;
    height: number;
    valid: boolean;
}
interface ESEngineModule {
    Registry: new () => CppRegistry;
    HEAPU8: Uint8Array;
    HEAPU32: Uint32Array;
    HEAPF32: Float32Array;
    FS: EmscriptenFS;
    materialDataProvider?: (materialId: number, outShaderIdPtr: number, outBlendModePtr: number, outUniformBufferPtr: number, outUniformCountPtr: number) => void;
    initRenderer(): void;
    initRendererWithCanvas(canvasSelector: string): boolean;
    initRendererWithContext(contextHandle: number): boolean;
    shutdownRenderer(): void;
    GL: {
        registerContext(ctx: WebGLRenderingContext | WebGL2RenderingContext, options: {
            majorVersion: number;
            minorVersion: number;
            enableExtensionsByDefault?: boolean;
        }): number;
    };
    renderFrame(registry: CppRegistry, width: number, height: number): void;
    renderFrameWithMatrix(registry: CppRegistry, width: number, height: number, matrixPtr: number): void;
    getResourceManager(): CppResourceManager;
    getSpineBounds?(registry: CppRegistry, entity: number): SpineBounds;
    spine_update?(registry: CppRegistry, dt: number): void;
    spine_play?(entity: number, animation: string, loop: boolean, track: number): boolean;
    spine_addAnimation?(entity: number, animation: string, loop: boolean, delay: number, track: number): boolean;
    spine_setSkin?(entity: number, skinName: string): boolean;
    spine_getBonePosition?(entity: number, boneName: string): {
        x: number;
        y: number;
    } | null;
    spine_hasInstance?(entity: number): boolean;
    spine_reloadAssets?(registry: CppRegistry): void;
    spine_getAnimations?(entity: number): string[];
    spine_getSkins?(entity: number): string[];
    spine_setNeedsReload?(registry: CppRegistry, entity: number, value: boolean): void;
    renderer_submitSpineBatch?(verticesPtr: number, vertexCount: number, indicesPtr: number, indexCount: number, textureId: number, blendMode: number, transformPtr: number, entity: number, layer: number, depth: number): void;
    renderer_submitSpineBatchByEntity?(registry: CppRegistry, verticesPtr: number, vertexCount: number, indicesPtr: number, indexCount: number, textureId: number, blendMode: number, entity: number, skelScale: number, flipX: boolean, flipY: boolean, layer: number, depth: number): void;
    invalidateMaterialCache(materialId: number): void;
    clearMaterialCache(): void;
    draw_begin(matrixPtr: number): void;
    draw_end(): void;
    draw_line(fromX: number, fromY: number, toX: number, toY: number, r: number, g: number, b: number, a: number, thickness: number): void;
    draw_rect(x: number, y: number, width: number, height: number, r: number, g: number, b: number, a: number, filled: boolean): void;
    draw_rectOutline(x: number, y: number, width: number, height: number, r: number, g: number, b: number, a: number, thickness: number): void;
    draw_circle(centerX: number, centerY: number, radius: number, r: number, g: number, b: number, a: number, filled: boolean, segments: number): void;
    draw_circleOutline(centerX: number, centerY: number, radius: number, r: number, g: number, b: number, a: number, thickness: number, segments: number): void;
    draw_texture(x: number, y: number, width: number, height: number, textureId: number, r: number, g: number, b: number, a: number): void;
    draw_textureRotated(x: number, y: number, width: number, height: number, rotation: number, textureId: number, r: number, g: number, b: number, a: number): void;
    draw_setLayer(layer: number): void;
    draw_setDepth(depth: number): void;
    draw_getDrawCallCount(): number;
    draw_getPrimitiveCount(): number;
    draw_setBlendMode(mode: number): void;
    draw_setDepthTest(enabled: boolean): void;
    draw_mesh(geometryHandle: number, shaderHandle: number, transformPtr: number): void;
    draw_meshWithUniforms(geometryHandle: number, shaderHandle: number, transformPtr: number, uniformsPtr: number, uniformCount: number): void;
    geometry_create(): number;
    geometry_init(handle: number, verticesPtr: number, vertexCount: number, layoutPtr: number, layoutCount: number, dynamic: boolean): void;
    geometry_setIndices16(handle: number, indicesPtr: number, indexCount: number): void;
    geometry_setIndices32(handle: number, indicesPtr: number, indexCount: number): void;
    geometry_updateVertices(handle: number, verticesPtr: number, vertexCount: number, offset: number): void;
    geometry_release(handle: number): void;
    geometry_isValid(handle: number): boolean;
    postprocess_init(width: number, height: number): boolean;
    postprocess_shutdown(): void;
    postprocess_resize(width: number, height: number): void;
    postprocess_addPass(name: string, shaderHandle: number): number;
    postprocess_removePass(name: string): void;
    postprocess_setPassEnabled(name: string, enabled: boolean): void;
    postprocess_isPassEnabled(name: string): boolean;
    postprocess_setUniformFloat(passName: string, uniform: string, value: number): void;
    postprocess_setUniformVec4(passName: string, uniform: string, x: number, y: number, z: number, w: number): void;
    postprocess_begin(): void;
    postprocess_end(): void;
    postprocess_getPassCount(): number;
    postprocess_isInitialized(): boolean;
    postprocess_setBypass(bypass: boolean): void;
    postprocess_isBypassed(): boolean;
    postprocess_clearPasses(): void;
    postprocess_setOutputTarget(fboId: number): void;
    postprocess_setOutputViewport(x: number, y: number, w: number, h: number): void;
    postprocess_beginScreenCapture(): void;
    postprocess_endScreenCapture(): void;
    postprocess_executeScreenPasses(): void;
    postprocess_addScreenPass(name: string, shaderHandle: number): number;
    postprocess_clearScreenPasses(): void;
    postprocess_setScreenUniformFloat(passName: string, uniform: string, value: number): void;
    postprocess_setScreenUniformVec4(passName: string, uniform: string, x: number, y: number, z: number, w: number): void;
    renderer_init(width: number, height: number): void;
    renderer_resize(width: number, height: number): void;
    renderer_beginFrame(): void;
    renderer_updateTransforms(registry: CppRegistry): void;
    renderer_begin(matrixPtr: number, targetHandle: number): void;
    renderer_flush(): void;
    renderer_end(): void;
    renderer_submitSprites(registry: CppRegistry): void;
    renderer_submitUIElements(registry: CppRegistry): void;
    renderer_submitBitmapText(registry: CppRegistry): void;
    renderer_submitShapes?(registry: CppRegistry): void;
    renderer_submitSpine?(registry: CppRegistry): void;
    renderer_submitParticles?(registry: CppRegistry): void;
    renderer_submitAll(registry: CppRegistry, skipFlags: number, vpX: number, vpY: number, vpW: number, vpH: number): void;
    particle_update?(registry: CppRegistry, dt: number): void;
    particle_play?(registry: CppRegistry, entity: number): void;
    particle_stop?(registry: CppRegistry, entity: number): void;
    particle_reset?(registry: CppRegistry, entity: number): void;
    particle_getAliveCount?(entity: number): number;
    tilemap_initLayer?(entity: number, width: number, height: number, tileWidth: number, tileHeight: number): void;
    tilemap_destroyLayer?(entity: number): void;
    tilemap_setTile?(entity: number, x: number, y: number, tileId: number): void;
    tilemap_getTile?(entity: number, x: number, y: number): number;
    tilemap_fillRect?(entity: number, x: number, y: number, w: number, h: number, tileId: number): void;
    tilemap_setTiles?(entity: number, tilesPtr: number, count: number): void;
    tilemap_hasLayer?(entity: number): boolean;
    tilemap_submitLayer?(entity: number, textureId: number, sortLayer: number, depth: number, tilesetColumns: number, uvTileWidth: number, uvTileHeight: number, originX: number, originY: number, camLeft: number, camBottom: number, camRight: number, camTop: number): void;
    renderer_setStage(stage: number): void;
    renderer_createTarget(width: number, height: number, flags: number): number;
    renderer_releaseTarget(handle: number): void;
    renderer_getTargetTexture(handle: number): number;
    renderer_getTargetDepthTexture(handle: number): number;
    renderer_getDrawCalls(): number;
    renderer_getTriangles(): number;
    renderer_getSprites(): number;
    renderer_getText(): number;
    renderer_getSpine?(): number;
    renderer_getMeshes(): number;
    renderer_getCulled(): number;
    renderer_setClearColor(r: number, g: number, b: number, a: number): void;
    renderer_setViewport(x: number, y: number, w: number, h: number): void;
    renderer_setScissor(x: number, y: number, w: number, h: number, enable: boolean): void;
    renderer_clearBuffers(flags: number): void;
    renderer_setEntityClipRect(entity: number, x: number, y: number, w: number, h: number): void;
    renderer_clearEntityClipRect(entity: number): void;
    renderer_clearAllClipRects(): void;
    renderer_clearStencil(): void;
    renderer_setEntityStencilMask(entity: number, refValue: number): void;
    renderer_setEntityStencilTest(entity: number, refValue: number): void;
    renderer_clearEntityStencilMask(entity: number): void;
    renderer_clearAllStencilMasks(): void;
    registry_getCanvasEntity(registry: CppRegistry): number;
    registry_getCameraEntities(registry: CppRegistry): number[];
    getChildEntities(registry: CppRegistry, entity: number): number[];
    registry_getGeneration(registry: CppRegistry, entity: number): number;
    registry_getSchemaPoolVersion(registry: CppRegistry, poolId: number): number;
    registry_batchSyncPhysicsTransforms(registry: CppRegistry, bufferPtr: number, count: number, ppu: number): void;
    gl_enableErrorCheck(enabled: boolean): void;
    gl_checkErrors(context: string): number;
    renderer_diagnose(): void;
    renderer_captureNextFrame(): void;
    renderer_getCapturedFrameSize(): number;
    renderer_getCapturedFrameData(): number;
    renderer_getCapturedEntities(): number;
    renderer_getCapturedEntityCount(): number;
    renderer_getCapturedCameraCount(): number;
    renderer_hasCapturedData(): boolean;
    renderer_replayToDrawCall(drawCallIndex: number): void;
    renderer_getSnapshotPtr(): number;
    renderer_getSnapshotSize(): number;
    renderer_getSnapshotWidth(): number;
    renderer_getSnapshotHeight(): number;
    uiLayout_update(registry: CppRegistry, camLeft: number, camBottom: number, camRight: number, camTop: number): void;
    uiHitTest_update(registry: CppRegistry, mouseWorldX: number, mouseWorldY: number, mouseDown: boolean, mousePressed: boolean, mouseReleased: boolean): void;
    uiHitTest_getHitEntity(): number;
    uiHitTest_getHitEntityPrev(): number;
    uiRenderOrder_update(registry: CppRegistry): void;
    uiFlexLayout_update(registry: CppRegistry): void;
    getUIRectComputedWidth(registry: CppRegistry, entity: number): number;
    getUIRectComputedHeight(registry: CppRegistry, entity: number): number;
    setUIRectSize(registry: CppRegistry, entity: number, w: number, h: number): void;
    uiTree_markStructureDirty(): void;
    uiTree_markDirty(entity: number): void;
    uiTree_markAllDirty(): void;
    transform_update(registry: CppRegistry): void;
    uiRect_clearAnimOverrides(registry: CppRegistry): void;
    uiRect_setAnimOverride(registry: CppRegistry, entity: number, flags: number): void;
    uiRect_patchOffset(registry: CppRegistry, entity: number, minX: number, minY: number, maxX: number, maxY: number): void;
    transform_patchPosition(registry: CppRegistry, entity: number, x: number, y: number, z: number): void;
    _anim_createTween(registry: CppRegistry, entity: number, targetProp: number, from: number, to: number, duration: number, easing: number, delay: number, loopMode: number, loopCount: number): number;
    _anim_cancelTween(registry: CppRegistry, tweenEntity: number): void;
    _anim_cancelAllTweens(registry: CppRegistry, targetEntity: number): void;
    _anim_pauseTween(registry: CppRegistry, tweenEntity: number): void;
    _anim_resumeTween(registry: CppRegistry, tweenEntity: number): void;
    _anim_setTweenBezier(registry: CppRegistry, tweenEntity: number, p1x: number, p1y: number, p2x: number, p2y: number): void;
    _anim_setSequenceNext(registry: CppRegistry, tweenEntity: number, nextEntity: number): void;
    _anim_updateTweens(registry: CppRegistry, deltaTime: number): void;
    _anim_getTweenState(registry: CppRegistry, tweenEntity: number): number;
    _tl_create(duration: number, wrapMode: number): number;
    _tl_destroy(handle: number): void;
    _tl_addPropertyTrack(handle: number, childPathPtr: number, childPathLen: number, component: number, fieldsPtr: number, channelCount: number, keyframeDataPtr: number, keyframeCountsPtr: number): void;
    _tl_addCustomPropertyTrack(handle: number, childPathPtr: number, childPathLen: number, componentNamePtr: number, componentNameLen: number, fieldPathsPtr: number, fieldPathLensPtr: number, channelCount: number, keyframeDataPtr: number, keyframeCountsPtr: number): void;
    _tl_addSpineTrack(handle: number, childPathPtr: number, childPathLen: number, clipsDataPtr: number, clipAnimPtrs: number, clipAnimLens: number, clipCount: number, blendIn: number): void;
    _tl_addAudioTrack(handle: number, childPathPtr: number, childPathLen: number, eventsFloatPtr: number, clipPtrs: number, clipLens: number, eventCount: number): void;
    _tl_addActivationTrack(handle: number, childPathPtr: number, childPathLen: number, rangesPtr: number, rangeCount: number): void;
    _tl_addSpriteAnimTrack(handle: number, childPathPtr: number, childPathLen: number, clipPathPtr: number, clipPathLen: number, startTime: number): void;
    _tl_play(handle: number): void;
    _tl_pause(handle: number): void;
    _tl_stop(handle: number): void;
    _tl_setTime(handle: number, time: number): void;
    _tl_setSpeed(handle: number, speed: number): void;
    _tl_setWrapMode(handle: number, mode: number): void;
    _tl_getTime(handle: number): number;
    _tl_isPlaying(handle: number): number;
    _tl_advance(registry: CppRegistry, handle: number, rootEntity: number, deltaTime: number, speed: number): void;
    _tl_evaluateAt(handle: number, time: number, outPtr: number, maxChannels: number): number;
    _tl_getEventCount(): number;
    _tl_getEventType(index: number): number;
    _tl_getEventEntity(index: number): number;
    _tl_getEventIntParam(index: number): number;
    _tl_getEventFloatParam(index: number): number;
    _tl_getEventString(index: number): number;
    _tl_getEventStringLen(index: number): number;
    _tl_getCustomPropertyCount(): number;
    _tl_getCustomPropertyEntity(index: number): number;
    _tl_getCustomPropertyTrackIndex(index: number): number;
    _tl_getCustomPropertyChannelIndex(index: number): number;
    _tl_getCustomPropertyValue(index: number): number;
    _tl_clearResults(): void;
    _tl_setTrackTarget(handle: number, isEventTrack: number, trackIndex: number, entity: number): void;
    getTransformPtr(registry: CppRegistry, entity: number): number;
    getSpritePtr(registry: CppRegistry, entity: number): number;
    getVelocityPtr(registry: CppRegistry, entity: number): number;
    getCameraPtr(registry: CppRegistry, entity: number): number;
    getUIRectPtr(registry: CppRegistry, entity: number): number;
    getRigidBodyPtr(registry: CppRegistry, entity: number): number;
    getBoxColliderPtr(registry: CppRegistry, entity: number): number;
    getCircleColliderPtr(registry: CppRegistry, entity: number): number;
    _malloc(size: number): number;
    _free(ptr: number): void;
}

export { INVALID_ENTITY as I, INVALID_FONT as f, INVALID_MATERIAL as g, INVALID_TEXTURE as h, color as i, vec3 as j, vec4 as k, quat as q, vec2 as v };
export type { CppRegistry as C, Entity as E, FontHandle as F, Padding as P, Quat as Q, SpineBounds as S, TextureHandle as T, Vec2 as V, ESEngineModule as a, Color as b, Vec3 as c, Vec4 as d, CppResourceManager as e, EmscriptenFS as l };
