/**
 * @file    WebBindings.generated.cpp
 * @brief   Auto-generated Emscripten embind bindings
 * @details Generated by EHT (ESEngine Header Tool) - DO NOT EDIT
 *
 * @author  ESEngine Team
 * @date    2026
 *
 * @copyright Copyright (c) 2026 ESEngine Team
 *            Licensed under the MIT License.
 */

#ifdef ES_PLATFORM_WEB

#include <emscripten/bind.h>
#include "../ecs/Registry.hpp"
#include "../math/Math.hpp"
#include "../resource/ResourceManager.hpp"
#include "../renderer/Texture.hpp"
#include "../renderer/Shader.hpp"
#include "../app/App.hpp"
#include "../app/Schedule.hpp"

#include "../ecs/components/Camera.hpp"
#include "../ecs/components/Canvas.hpp"
#include "../ecs/components/Hierarchy.hpp"
#include "../ecs/components/Sprite.hpp"
#include "../ecs/components/Transform.hpp"
#include "../ecs/components/Velocity.hpp"

using namespace emscripten;
using namespace esengine;
using namespace esengine::ecs;

// =============================================================================
// Enums
// =============================================================================

EMSCRIPTEN_BINDINGS(esengine_enums) {
    enum_<esengine::ecs::ProjectionType>("ProjectionType")
        .value("Perspective", esengine::ecs::ProjectionType::Perspective)
        .value("Orthographic", esengine::ecs::ProjectionType::Orthographic);

    enum_<esengine::ecs::CanvasScaleMode>("CanvasScaleMode")
        .value("FixedWidth", esengine::ecs::CanvasScaleMode::FixedWidth)
        .value("FixedHeight", esengine::ecs::CanvasScaleMode::FixedHeight)
        .value("Expand", esengine::ecs::CanvasScaleMode::Expand)
        .value("Shrink", esengine::ecs::CanvasScaleMode::Shrink)
        .value("Match", esengine::ecs::CanvasScaleMode::Match);
}

// =============================================================================
// Math Types
// =============================================================================

EMSCRIPTEN_BINDINGS(esengine_math) {
    value_object<glm::vec2>("Vec2")
        .field("x", &glm::vec2::x)
        .field("y", &glm::vec2::y);

    value_object<glm::vec3>("Vec3")
        .field("x", &glm::vec3::x)
        .field("y", &glm::vec3::y)
        .field("z", &glm::vec3::z);

    value_object<glm::vec4>("Vec4")
        .field("x", &glm::vec4::x)
        .field("y", &glm::vec4::y)
        .field("z", &glm::vec4::z)
        .field("w", &glm::vec4::w);

    value_object<glm::uvec2>("UVec2")
        .field("x", &glm::uvec2::x)
        .field("y", &glm::uvec2::y);

    value_object<glm::quat>("Quat")
        .field("w", &glm::quat::w)
        .field("x", &glm::quat::x)
        .field("y", &glm::quat::y)
        .field("z", &glm::quat::z);
}

// =============================================================================
// Components
// =============================================================================

EMSCRIPTEN_BINDINGS(esengine_components) {
    // Camera
    value_object<esengine::ecs::Camera>("Camera")
        .field("projectionType", &esengine::ecs::Camera::projectionType)
        .field("fov", &esengine::ecs::Camera::fov)
        .field("orthoSize", &esengine::ecs::Camera::orthoSize)
        .field("nearPlane", &esengine::ecs::Camera::nearPlane)
        .field("farPlane", &esengine::ecs::Camera::farPlane)
        .field("aspectRatio", &esengine::ecs::Camera::aspectRatio)
        .field("isActive", &esengine::ecs::Camera::isActive)
        .field("priority", &esengine::ecs::Camera::priority);

    // Canvas
    value_object<esengine::ecs::Canvas>("Canvas")
        .field("pixelsPerUnit", &esengine::ecs::Canvas::pixelsPerUnit)
        .field("scaleMode", &esengine::ecs::Canvas::scaleMode)
        .field("matchWidthOrHeight", &esengine::ecs::Canvas::matchWidthOrHeight)
        .field("backgroundColor", &esengine::ecs::Canvas::backgroundColor);

    // Parent
    value_object<esengine::ecs::Parent>("Parent")
        .field("entity", &esengine::ecs::Parent::entity);

    // Children
    value_object<esengine::ecs::Children>("Children");

    // Sprite
    value_object<esengine::ecs::Sprite>("Sprite")
        .field("color", &esengine::ecs::Sprite::color)
        .field("size", &esengine::ecs::Sprite::size)
        .field("uvOffset", &esengine::ecs::Sprite::uvOffset)
        .field("uvScale", &esengine::ecs::Sprite::uvScale)
        .field("layer", &esengine::ecs::Sprite::layer)
        .field("flipX", &esengine::ecs::Sprite::flipX)
        .field("flipY", &esengine::ecs::Sprite::flipY);

    // LocalTransform
    value_object<esengine::ecs::LocalTransform>("LocalTransform")
        .field("position", &esengine::ecs::LocalTransform::position)
        .field("rotation", &esengine::ecs::LocalTransform::rotation)
        .field("scale", &esengine::ecs::LocalTransform::scale);

    // WorldTransform
    value_object<esengine::ecs::WorldTransform>("WorldTransform")
        .field("position", &esengine::ecs::WorldTransform::position)
        .field("rotation", &esengine::ecs::WorldTransform::rotation)
        .field("scale", &esengine::ecs::WorldTransform::scale);

    // Velocity
    value_object<esengine::ecs::Velocity>("Velocity")
        .field("linear", &esengine::ecs::Velocity::linear)
        .field("angular", &esengine::ecs::Velocity::angular);

}

// =============================================================================
// Registry
// =============================================================================

EMSCRIPTEN_BINDINGS(esengine_registry) {
    class_<Registry>("Registry")
        .function("create", optional_override([](Registry& r) {
            return static_cast<u32>(r.create());
        }))
        .function("destroy", optional_override([](Registry& r, u32 e) {
            r.destroy(static_cast<Entity>(e));
        }))
        .function("valid", optional_override([](Registry& r, u32 e) {
            return r.valid(static_cast<Entity>(e));
        }))
        .function("entityCount", &Registry::entityCount)

        // Camera
        .function("hasCamera", optional_override([](Registry& r, u32 e) {
            return r.has<esengine::ecs::Camera>(static_cast<Entity>(e));
        }))
        .function("getCamera", optional_override([](Registry& r, u32 e) -> esengine::ecs::Camera& {
            return r.get<esengine::ecs::Camera>(static_cast<Entity>(e));
        }), allow_raw_pointers())
        .function("addCamera", optional_override([](Registry& r, u32 e, const esengine::ecs::Camera& c) {
            r.emplaceOrReplace<esengine::ecs::Camera>(static_cast<Entity>(e), c);
        }))
        .function("removeCamera", optional_override([](Registry& r, u32 e) {
            r.remove<esengine::ecs::Camera>(static_cast<Entity>(e));
        }))

        // Canvas
        .function("hasCanvas", optional_override([](Registry& r, u32 e) {
            return r.has<esengine::ecs::Canvas>(static_cast<Entity>(e));
        }))
        .function("getCanvas", optional_override([](Registry& r, u32 e) -> esengine::ecs::Canvas& {
            return r.get<esengine::ecs::Canvas>(static_cast<Entity>(e));
        }), allow_raw_pointers())
        .function("addCanvas", optional_override([](Registry& r, u32 e, const esengine::ecs::Canvas& c) {
            r.emplaceOrReplace<esengine::ecs::Canvas>(static_cast<Entity>(e), c);
        }))
        .function("removeCanvas", optional_override([](Registry& r, u32 e) {
            r.remove<esengine::ecs::Canvas>(static_cast<Entity>(e));
        }))

        // Parent
        .function("hasParent", optional_override([](Registry& r, u32 e) {
            return r.has<esengine::ecs::Parent>(static_cast<Entity>(e));
        }))
        .function("getParent", optional_override([](Registry& r, u32 e) -> esengine::ecs::Parent& {
            return r.get<esengine::ecs::Parent>(static_cast<Entity>(e));
        }), allow_raw_pointers())
        .function("addParent", optional_override([](Registry& r, u32 e, const esengine::ecs::Parent& c) {
            r.emplaceOrReplace<esengine::ecs::Parent>(static_cast<Entity>(e), c);
        }))
        .function("removeParent", optional_override([](Registry& r, u32 e) {
            r.remove<esengine::ecs::Parent>(static_cast<Entity>(e));
        }))

        // Children
        .function("hasChildren", optional_override([](Registry& r, u32 e) {
            return r.has<esengine::ecs::Children>(static_cast<Entity>(e));
        }))
        .function("getChildren", optional_override([](Registry& r, u32 e) -> esengine::ecs::Children& {
            return r.get<esengine::ecs::Children>(static_cast<Entity>(e));
        }), allow_raw_pointers())
        .function("addChildren", optional_override([](Registry& r, u32 e, const esengine::ecs::Children& c) {
            r.emplaceOrReplace<esengine::ecs::Children>(static_cast<Entity>(e), c);
        }))
        .function("removeChildren", optional_override([](Registry& r, u32 e) {
            r.remove<esengine::ecs::Children>(static_cast<Entity>(e));
        }))

        // Sprite
        .function("hasSprite", optional_override([](Registry& r, u32 e) {
            return r.has<esengine::ecs::Sprite>(static_cast<Entity>(e));
        }))
        .function("getSprite", optional_override([](Registry& r, u32 e) -> esengine::ecs::Sprite& {
            return r.get<esengine::ecs::Sprite>(static_cast<Entity>(e));
        }), allow_raw_pointers())
        .function("addSprite", optional_override([](Registry& r, u32 e, const esengine::ecs::Sprite& c) {
            r.emplaceOrReplace<esengine::ecs::Sprite>(static_cast<Entity>(e), c);
        }))
        .function("removeSprite", optional_override([](Registry& r, u32 e) {
            r.remove<esengine::ecs::Sprite>(static_cast<Entity>(e));
        }))

        // LocalTransform
        .function("hasLocalTransform", optional_override([](Registry& r, u32 e) {
            return r.has<esengine::ecs::LocalTransform>(static_cast<Entity>(e));
        }))
        .function("getLocalTransform", optional_override([](Registry& r, u32 e) -> esengine::ecs::LocalTransform& {
            return r.get<esengine::ecs::LocalTransform>(static_cast<Entity>(e));
        }), allow_raw_pointers())
        .function("addLocalTransform", optional_override([](Registry& r, u32 e, const esengine::ecs::LocalTransform& c) {
            r.emplaceOrReplace<esengine::ecs::LocalTransform>(static_cast<Entity>(e), c);
        }))
        .function("removeLocalTransform", optional_override([](Registry& r, u32 e) {
            r.remove<esengine::ecs::LocalTransform>(static_cast<Entity>(e));
        }))

        // WorldTransform
        .function("hasWorldTransform", optional_override([](Registry& r, u32 e) {
            return r.has<esengine::ecs::WorldTransform>(static_cast<Entity>(e));
        }))
        .function("getWorldTransform", optional_override([](Registry& r, u32 e) -> esengine::ecs::WorldTransform& {
            return r.get<esengine::ecs::WorldTransform>(static_cast<Entity>(e));
        }), allow_raw_pointers())
        .function("addWorldTransform", optional_override([](Registry& r, u32 e, const esengine::ecs::WorldTransform& c) {
            r.emplaceOrReplace<esengine::ecs::WorldTransform>(static_cast<Entity>(e), c);
        }))
        .function("removeWorldTransform", optional_override([](Registry& r, u32 e) {
            r.remove<esengine::ecs::WorldTransform>(static_cast<Entity>(e));
        }))

        // Velocity
        .function("hasVelocity", optional_override([](Registry& r, u32 e) {
            return r.has<esengine::ecs::Velocity>(static_cast<Entity>(e));
        }))
        .function("getVelocity", optional_override([](Registry& r, u32 e) -> esengine::ecs::Velocity& {
            return r.get<esengine::ecs::Velocity>(static_cast<Entity>(e));
        }), allow_raw_pointers())
        .function("addVelocity", optional_override([](Registry& r, u32 e, const esengine::ecs::Velocity& c) {
            r.emplaceOrReplace<esengine::ecs::Velocity>(static_cast<Entity>(e), c);
        }))
        .function("removeVelocity", optional_override([](Registry& r, u32 e) {
            r.remove<esengine::ecs::Velocity>(static_cast<Entity>(e));
        }))

        ;
}

// =============================================================================
// Resource Manager
// =============================================================================

EMSCRIPTEN_BINDINGS(esengine_resources) {
    using namespace esengine::resource;

    class_<ResourceManager>("ResourceManager")
        .constructor<>()
        .function("init", &ResourceManager::init)
        .function("shutdown", &ResourceManager::shutdown)
        .function("createShader", optional_override([](ResourceManager& rm,
            const std::string& vertSrc, const std::string& fragSrc) -> u32 {
            return rm.createShader(vertSrc, fragSrc).id();
        }))
        .function("createTexture", optional_override([](ResourceManager& rm,
            u32 width, u32 height, uintptr_t pixelsPtr, usize pixelsLen, int format) -> u32 {
            const u8* pixels = reinterpret_cast<const u8*>(pixelsPtr);
            ConstSpan<u8> span(pixels, pixelsLen);
            return rm.createTexture(width, height, span,
                static_cast<TextureFormat>(format)).id();
        }))
        .function("releaseShader", optional_override([](ResourceManager& rm, u32 handle) {
            rm.releaseShader(ShaderHandle(handle));
        }))
        .function("releaseTexture", optional_override([](ResourceManager& rm, u32 handle) {
            rm.releaseTexture(TextureHandle(handle));
        }));

    enum_<TextureFormat>("TextureFormat")
        .value("RGB8", TextureFormat::RGB8)
        .value("RGBA8", TextureFormat::RGBA8);
}

// =============================================================================
// App
// =============================================================================

EMSCRIPTEN_BINDINGS(esengine_app) {
    enum_<Schedule>("Schedule")
        .value("Startup", Schedule::Startup)
        .value("PreUpdate", Schedule::PreUpdate)
        .value("Update", Schedule::Update)
        .value("PostUpdate", Schedule::PostUpdate)
        .value("PreRender", Schedule::PreRender)
        .value("Render", Schedule::Render)
        .value("PostRender", Schedule::PostRender);

    value_object<Time>("Time")
        .field("delta", &Time::delta)
        .field("elapsed", &Time::elapsed)
        .field("frameCount", &Time::frameCount);

    value_object<AppConfig>("AppConfig")
        .field("title", &AppConfig::title)
        .field("width", &AppConfig::width)
        .field("height", &AppConfig::height)
        .field("vsync", &AppConfig::vsync);

    class_<App>("App")
        .function("run", &App::run)
        .function("quit", &App::quit)
        .function("registry", optional_override([](App& app) -> Registry* {
            return &app.registry();
        }), allow_raw_pointers())
        .function("time", &App::time)
        .function("width", &App::width)
        .function("height", &App::height);

    function("createApp", optional_override([]() -> App* {
        static App app;
        return &app;
    }), allow_raw_pointers());

    function("createAppWithConfig", optional_override([](const AppConfig& config) -> App* {
        static App app(config);
        return &app;
    }), allow_raw_pointers());

    function("getApp", optional_override([]() -> App* {
        return &App::get();
    }), allow_raw_pointers());

    function("setJSSystemsCallback", optional_override([](emscripten::val callback) {
        static emscripten::val storedCallback = emscripten::val::undefined();
        storedCallback = callback;
        App::setJSSystemsCallback(&storedCallback);
    }));
}

// =============================================================================
// View Iterator for Query
// =============================================================================

EMSCRIPTEN_BINDINGS(esengine_query) {
    class_<std::vector<u32>>("EntityVector")
        .constructor<>()
        .function("size", &std::vector<u32>::size)
        .function("get", optional_override([](const std::vector<u32>& v, usize i) {
            return v[i];
        }));

    function("queryLocalTransformSprite", optional_override([](Registry& reg) {
        std::vector<u32> entities;
        reg.each<LocalTransform, Sprite>([&entities](Entity e, LocalTransform&, Sprite&) {
            entities.push_back(static_cast<u32>(e));
        });
        return entities;
    }));

    function("queryLocalTransform", optional_override([](Registry& reg) {
        std::vector<u32> entities;
        reg.each<LocalTransform>([&entities](Entity e, LocalTransform&) {
            entities.push_back(static_cast<u32>(e));
        });
        return entities;
    }));
}

#endif  // ES_PLATFORM_WEB
