/**
 * @file    WebBindings.generated.cpp
 * @brief   Auto-generated Emscripten embind bindings
 * @details Generated by EHT - DO NOT EDIT
 *
 * @copyright Copyright (c) 2026 ESEngine Team
 */

#ifdef ES_PLATFORM_WEB

#include <emscripten/bind.h>
#include "../ecs/Registry.hpp"
#include "../math/Math.hpp"
#include "../ecs/TransformSystem.hpp"
#include "../ecs/components/BitmapText.hpp"
#include "../ecs/components/Camera.hpp"
#include "../ecs/components/Canvas.hpp"
#include "../ecs/components/Collider.hpp"
#include "../ecs/components/Hierarchy.hpp"
#include "../ecs/components/RigidBody.hpp"
#include "../ecs/components/SpineAnimation.hpp"
#include "../ecs/components/Sprite.hpp"
#include "../ecs/components/Transform.hpp"
#include "../ecs/components/Velocity.hpp"

using namespace emscripten;
using namespace esengine;
using namespace esengine::ecs;

// =============================================================================
// Math Types
// =============================================================================

EMSCRIPTEN_BINDINGS(esengine_math) {
    value_object<glm::vec2>("Vec2")
        .field("x", &glm::vec2::x)
        .field("y", &glm::vec2::y);

    value_object<glm::vec3>("Vec3")
        .field("x", &glm::vec3::x)
        .field("y", &glm::vec3::y)
        .field("z", &glm::vec3::z);

    value_object<glm::vec4>("Vec4")
        .field("x", &glm::vec4::x)
        .field("y", &glm::vec4::y)
        .field("z", &glm::vec4::z)
        .field("w", &glm::vec4::w);

    value_object<glm::uvec2>("UVec2")
        .field("x", &glm::uvec2::x)
        .field("y", &glm::uvec2::y);

    value_object<glm::quat>("Quat")
        .field("w", &glm::quat::w)
        .field("x", &glm::quat::x)
        .field("y", &glm::quat::y)
        .field("z", &glm::quat::z);
}

// =============================================================================
// Enums
// =============================================================================

EMSCRIPTEN_BINDINGS(esengine_enums) {
    enum_<esengine::ecs::BodyType>("BodyType")
        .value("Static", esengine::ecs::BodyType::Static)
        .value("Kinematic", esengine::ecs::BodyType::Kinematic)
        .value("Dynamic", esengine::ecs::BodyType::Dynamic);

    enum_<esengine::ecs::TextAlign>("TextAlign")
        .value("Left", esengine::ecs::TextAlign::Left)
        .value("Center", esengine::ecs::TextAlign::Center)
        .value("Right", esengine::ecs::TextAlign::Right);

    enum_<esengine::ecs::CanvasScaleMode>("CanvasScaleMode")
        .value("FixedWidth", esengine::ecs::CanvasScaleMode::FixedWidth)
        .value("FixedHeight", esengine::ecs::CanvasScaleMode::FixedHeight)
        .value("Expand", esengine::ecs::CanvasScaleMode::Expand)
        .value("Shrink", esengine::ecs::CanvasScaleMode::Shrink)
        .value("Match", esengine::ecs::CanvasScaleMode::Match);

    enum_<esengine::ecs::ProjectionType>("ProjectionType")
        .value("Perspective", esengine::ecs::ProjectionType::Perspective)
        .value("Orthographic", esengine::ecs::ProjectionType::Orthographic);

}

// =============================================================================
// Components
// =============================================================================

struct RigidBodyJS {
    i32 bodyType;
    f32 gravityScale;
    f32 linearDamping;
    f32 angularDamping;
    bool fixedRotation;
    bool bullet;
    bool enabled;
};

esengine::ecs::RigidBody rigidbodyFromJS(const RigidBodyJS& js) {
    esengine::ecs::RigidBody c;
    c.bodyType = static_cast<BodyType>(js.bodyType);
    c.gravityScale = js.gravityScale;
    c.linearDamping = js.linearDamping;
    c.angularDamping = js.angularDamping;
    c.fixedRotation = js.fixedRotation;
    c.bullet = js.bullet;
    c.enabled = js.enabled;
    return c;
}

RigidBodyJS rigidbodyToJS(const esengine::ecs::RigidBody& c) {
    RigidBodyJS js;
    js.bodyType = static_cast<i32>(c.bodyType);
    js.gravityScale = c.gravityScale;
    js.linearDamping = c.linearDamping;
    js.angularDamping = c.angularDamping;
    js.fixedRotation = c.fixedRotation;
    js.bullet = c.bullet;
    js.enabled = c.enabled;
    return js;
}

struct BitmapTextJS {
    std::string text;
    glm::vec4 color;
    f32 fontSize;
    i32 align;
    f32 spacing;
    i32 layer;
    u32 font;
};

esengine::ecs::BitmapText bitmaptextFromJS(const BitmapTextJS& js) {
    esengine::ecs::BitmapText c;
    c.text = js.text;
    c.color = js.color;
    c.fontSize = js.fontSize;
    c.align = static_cast<TextAlign>(js.align);
    c.spacing = js.spacing;
    c.layer = js.layer;
    c.font = resource::BitmapFontHandle(js.font);
    return c;
}

BitmapTextJS bitmaptextToJS(const esengine::ecs::BitmapText& c) {
    BitmapTextJS js;
    js.text = c.text;
    js.color = c.color;
    js.fontSize = c.fontSize;
    js.align = static_cast<i32>(c.align);
    js.spacing = c.spacing;
    js.layer = c.layer;
    js.font = c.font.id();
    return js;
}

struct SpriteJS {
    u32 texture;
    glm::vec4 color;
    glm::vec2 size;
    glm::vec2 uvOffset;
    glm::vec2 uvScale;
    i32 layer;
    bool flipX;
    bool flipY;
    u32 material;
};

esengine::ecs::Sprite spriteFromJS(const SpriteJS& js) {
    esengine::ecs::Sprite c;
    c.texture = resource::TextureHandle(js.texture);
    c.color = js.color;
    c.size = js.size;
    c.uvOffset = js.uvOffset;
    c.uvScale = js.uvScale;
    c.layer = js.layer;
    c.flipX = js.flipX;
    c.flipY = js.flipY;
    c.material = js.material;
    return c;
}

SpriteJS spriteToJS(const esengine::ecs::Sprite& c) {
    SpriteJS js;
    js.texture = c.texture.id();
    js.color = c.color;
    js.size = c.size;
    js.uvOffset = c.uvOffset;
    js.uvScale = c.uvScale;
    js.layer = c.layer;
    js.flipX = c.flipX;
    js.flipY = c.flipY;
    js.material = c.material;
    return js;
}

struct CanvasJS {
    glm::uvec2 designResolution;
    f32 pixelsPerUnit;
    i32 scaleMode;
    f32 matchWidthOrHeight;
    glm::vec4 backgroundColor;
};

esengine::ecs::Canvas canvasFromJS(const CanvasJS& js) {
    esengine::ecs::Canvas c;
    c.designResolution = js.designResolution;
    c.pixelsPerUnit = js.pixelsPerUnit;
    c.scaleMode = static_cast<CanvasScaleMode>(js.scaleMode);
    c.matchWidthOrHeight = js.matchWidthOrHeight;
    c.backgroundColor = js.backgroundColor;
    return c;
}

CanvasJS canvasToJS(const esengine::ecs::Canvas& c) {
    CanvasJS js;
    js.designResolution = c.designResolution;
    js.pixelsPerUnit = c.pixelsPerUnit;
    js.scaleMode = static_cast<i32>(c.scaleMode);
    js.matchWidthOrHeight = c.matchWidthOrHeight;
    js.backgroundColor = c.backgroundColor;
    return js;
}

struct CameraJS {
    i32 projectionType;
    f32 fov;
    f32 orthoSize;
    f32 nearPlane;
    f32 farPlane;
    f32 aspectRatio;
    bool isActive;
    i32 priority;
    f32 viewportX;
    f32 viewportY;
    f32 viewportW;
    f32 viewportH;
    i32 clearFlags;
};

esengine::ecs::Camera cameraFromJS(const CameraJS& js) {
    esengine::ecs::Camera c;
    c.projectionType = static_cast<ProjectionType>(js.projectionType);
    c.fov = js.fov;
    c.orthoSize = js.orthoSize;
    c.nearPlane = js.nearPlane;
    c.farPlane = js.farPlane;
    c.aspectRatio = js.aspectRatio;
    c.isActive = js.isActive;
    c.priority = js.priority;
    c.viewportX = js.viewportX;
    c.viewportY = js.viewportY;
    c.viewportW = js.viewportW;
    c.viewportH = js.viewportH;
    c.clearFlags = js.clearFlags;
    return c;
}

CameraJS cameraToJS(const esengine::ecs::Camera& c) {
    CameraJS js;
    js.projectionType = static_cast<i32>(c.projectionType);
    js.fov = c.fov;
    js.orthoSize = c.orthoSize;
    js.nearPlane = c.nearPlane;
    js.farPlane = c.farPlane;
    js.aspectRatio = c.aspectRatio;
    js.isActive = c.isActive;
    js.priority = c.priority;
    js.viewportX = c.viewportX;
    js.viewportY = c.viewportY;
    js.viewportW = c.viewportW;
    js.viewportH = c.viewportH;
    js.clearFlags = c.clearFlags;
    return js;
}

EMSCRIPTEN_BINDINGS(esengine_components) {
    value_object<esengine::ecs::BoxCollider>("BoxCollider")
        .field("halfExtents", &esengine::ecs::BoxCollider::halfExtents)
        .field("offset", &esengine::ecs::BoxCollider::offset)
        .field("density", &esengine::ecs::BoxCollider::density)
        .field("friction", &esengine::ecs::BoxCollider::friction)
        .field("restitution", &esengine::ecs::BoxCollider::restitution)
        .field("isSensor", &esengine::ecs::BoxCollider::isSensor);

    value_object<esengine::ecs::CircleCollider>("CircleCollider")
        .field("radius", &esengine::ecs::CircleCollider::radius)
        .field("offset", &esengine::ecs::CircleCollider::offset)
        .field("density", &esengine::ecs::CircleCollider::density)
        .field("friction", &esengine::ecs::CircleCollider::friction)
        .field("restitution", &esengine::ecs::CircleCollider::restitution)
        .field("isSensor", &esengine::ecs::CircleCollider::isSensor);

    value_object<esengine::ecs::CapsuleCollider>("CapsuleCollider")
        .field("radius", &esengine::ecs::CapsuleCollider::radius)
        .field("halfHeight", &esengine::ecs::CapsuleCollider::halfHeight)
        .field("offset", &esengine::ecs::CapsuleCollider::offset)
        .field("density", &esengine::ecs::CapsuleCollider::density)
        .field("friction", &esengine::ecs::CapsuleCollider::friction)
        .field("restitution", &esengine::ecs::CapsuleCollider::restitution)
        .field("isSensor", &esengine::ecs::CapsuleCollider::isSensor);

    value_object<esengine::ecs::LocalTransform>("LocalTransform")
        .field("position", &esengine::ecs::LocalTransform::position)
        .field("rotation", &esengine::ecs::LocalTransform::rotation)
        .field("scale", &esengine::ecs::LocalTransform::scale);

    value_object<esengine::ecs::WorldTransform>("WorldTransform")
        .field("position", &esengine::ecs::WorldTransform::position)
        .field("rotation", &esengine::ecs::WorldTransform::rotation)
        .field("scale", &esengine::ecs::WorldTransform::scale);

    value_object<esengine::ecs::Velocity>("Velocity")
        .field("linear", &esengine::ecs::Velocity::linear)
        .field("angular", &esengine::ecs::Velocity::angular);

    value_object<esengine::ecs::SpineAnimation>("SpineAnimation")
        .field("skeletonPath", &esengine::ecs::SpineAnimation::skeletonPath)
        .field("atlasPath", &esengine::ecs::SpineAnimation::atlasPath)
        .field("skin", &esengine::ecs::SpineAnimation::skin)
        .field("animation", &esengine::ecs::SpineAnimation::animation)
        .field("timeScale", &esengine::ecs::SpineAnimation::timeScale)
        .field("loop", &esengine::ecs::SpineAnimation::loop)
        .field("playing", &esengine::ecs::SpineAnimation::playing)
        .field("flipX", &esengine::ecs::SpineAnimation::flipX)
        .field("flipY", &esengine::ecs::SpineAnimation::flipY)
        .field("color", &esengine::ecs::SpineAnimation::color)
        .field("layer", &esengine::ecs::SpineAnimation::layer)
        .field("skeletonScale", &esengine::ecs::SpineAnimation::skeletonScale)
        .field("material", &esengine::ecs::SpineAnimation::material);

    value_object<RigidBodyJS>("RigidBody")
        .field("bodyType", &RigidBodyJS::bodyType)
        .field("gravityScale", &RigidBodyJS::gravityScale)
        .field("linearDamping", &RigidBodyJS::linearDamping)
        .field("angularDamping", &RigidBodyJS::angularDamping)
        .field("fixedRotation", &RigidBodyJS::fixedRotation)
        .field("bullet", &RigidBodyJS::bullet)
        .field("enabled", &RigidBodyJS::enabled);

    value_object<BitmapTextJS>("BitmapText")
        .field("text", &BitmapTextJS::text)
        .field("color", &BitmapTextJS::color)
        .field("fontSize", &BitmapTextJS::fontSize)
        .field("align", &BitmapTextJS::align)
        .field("spacing", &BitmapTextJS::spacing)
        .field("layer", &BitmapTextJS::layer)
        .field("font", &BitmapTextJS::font);

    value_object<SpriteJS>("Sprite")
        .field("texture", &SpriteJS::texture)
        .field("color", &SpriteJS::color)
        .field("size", &SpriteJS::size)
        .field("uvOffset", &SpriteJS::uvOffset)
        .field("uvScale", &SpriteJS::uvScale)
        .field("layer", &SpriteJS::layer)
        .field("flipX", &SpriteJS::flipX)
        .field("flipY", &SpriteJS::flipY)
        .field("material", &SpriteJS::material);

    value_object<esengine::ecs::Parent>("Parent")
        .field("entity", &esengine::ecs::Parent::entity);

    value_object<esengine::ecs::Children>("Children");

    value_object<CanvasJS>("Canvas")
        .field("designResolution", &CanvasJS::designResolution)
        .field("pixelsPerUnit", &CanvasJS::pixelsPerUnit)
        .field("scaleMode", &CanvasJS::scaleMode)
        .field("matchWidthOrHeight", &CanvasJS::matchWidthOrHeight)
        .field("backgroundColor", &CanvasJS::backgroundColor);

    value_object<CameraJS>("Camera")
        .field("projectionType", &CameraJS::projectionType)
        .field("fov", &CameraJS::fov)
        .field("orthoSize", &CameraJS::orthoSize)
        .field("nearPlane", &CameraJS::nearPlane)
        .field("farPlane", &CameraJS::farPlane)
        .field("aspectRatio", &CameraJS::aspectRatio)
        .field("isActive", &CameraJS::isActive)
        .field("priority", &CameraJS::priority)
        .field("viewportX", &CameraJS::viewportX)
        .field("viewportY", &CameraJS::viewportY)
        .field("viewportW", &CameraJS::viewportW)
        .field("viewportH", &CameraJS::viewportH)
        .field("clearFlags", &CameraJS::clearFlags);

}

// =============================================================================
// Registry
// =============================================================================

EMSCRIPTEN_BINDINGS(esengine_registry) {
    class_<Registry>("Registry")
        .constructor<>()
        .function("create", optional_override([](Registry& r) {
            return static_cast<u32>(r.create());
        }))
        .function("destroy", optional_override([](Registry& r, u32 e) {
            r.destroy(static_cast<Entity>(e));
        }))
        .function("valid", optional_override([](Registry& r, u32 e) {
            return r.valid(static_cast<Entity>(e));
        }))
        .function("entityCount", &Registry::entityCount)

        // BoxCollider
        .function("hasBoxCollider", optional_override([](Registry& r, u32 e) {
            return r.has<esengine::ecs::BoxCollider>(static_cast<Entity>(e));
        }))
        .function("getBoxCollider", optional_override([](Registry& r, u32 e) -> esengine::ecs::BoxCollider& {
            return r.get<esengine::ecs::BoxCollider>(static_cast<Entity>(e));
        }), allow_raw_pointers())
        .function("addBoxCollider", optional_override([](Registry& r, u32 e, const esengine::ecs::BoxCollider& c) {
            r.emplaceOrReplace<esengine::ecs::BoxCollider>(static_cast<Entity>(e), c);
        }))
        .function("removeBoxCollider", optional_override([](Registry& r, u32 e) {
            r.remove<esengine::ecs::BoxCollider>(static_cast<Entity>(e));
        }))

        // CircleCollider
        .function("hasCircleCollider", optional_override([](Registry& r, u32 e) {
            return r.has<esengine::ecs::CircleCollider>(static_cast<Entity>(e));
        }))
        .function("getCircleCollider", optional_override([](Registry& r, u32 e) -> esengine::ecs::CircleCollider& {
            return r.get<esengine::ecs::CircleCollider>(static_cast<Entity>(e));
        }), allow_raw_pointers())
        .function("addCircleCollider", optional_override([](Registry& r, u32 e, const esengine::ecs::CircleCollider& c) {
            r.emplaceOrReplace<esengine::ecs::CircleCollider>(static_cast<Entity>(e), c);
        }))
        .function("removeCircleCollider", optional_override([](Registry& r, u32 e) {
            r.remove<esengine::ecs::CircleCollider>(static_cast<Entity>(e));
        }))

        // CapsuleCollider
        .function("hasCapsuleCollider", optional_override([](Registry& r, u32 e) {
            return r.has<esengine::ecs::CapsuleCollider>(static_cast<Entity>(e));
        }))
        .function("getCapsuleCollider", optional_override([](Registry& r, u32 e) -> esengine::ecs::CapsuleCollider& {
            return r.get<esengine::ecs::CapsuleCollider>(static_cast<Entity>(e));
        }), allow_raw_pointers())
        .function("addCapsuleCollider", optional_override([](Registry& r, u32 e, const esengine::ecs::CapsuleCollider& c) {
            r.emplaceOrReplace<esengine::ecs::CapsuleCollider>(static_cast<Entity>(e), c);
        }))
        .function("removeCapsuleCollider", optional_override([](Registry& r, u32 e) {
            r.remove<esengine::ecs::CapsuleCollider>(static_cast<Entity>(e));
        }))

        // LocalTransform
        .function("hasLocalTransform", optional_override([](Registry& r, u32 e) {
            return r.has<esengine::ecs::LocalTransform>(static_cast<Entity>(e));
        }))
        .function("getLocalTransform", optional_override([](Registry& r, u32 e) -> esengine::ecs::LocalTransform& {
            return r.get<esengine::ecs::LocalTransform>(static_cast<Entity>(e));
        }), allow_raw_pointers())
        .function("addLocalTransform", optional_override([](Registry& r, u32 e, const esengine::ecs::LocalTransform& c) {
            r.emplaceOrReplace<esengine::ecs::LocalTransform>(static_cast<Entity>(e), c);
        }))
        .function("removeLocalTransform", optional_override([](Registry& r, u32 e) {
            r.remove<esengine::ecs::LocalTransform>(static_cast<Entity>(e));
        }))

        // WorldTransform
        .function("hasWorldTransform", optional_override([](Registry& r, u32 e) {
            return r.has<esengine::ecs::WorldTransform>(static_cast<Entity>(e));
        }))
        .function("getWorldTransform", optional_override([](Registry& r, u32 e) -> esengine::ecs::WorldTransform& {
            return r.get<esengine::ecs::WorldTransform>(static_cast<Entity>(e));
        }), allow_raw_pointers())
        .function("addWorldTransform", optional_override([](Registry& r, u32 e, const esengine::ecs::WorldTransform& c) {
            r.emplaceOrReplace<esengine::ecs::WorldTransform>(static_cast<Entity>(e), c);
        }))
        .function("removeWorldTransform", optional_override([](Registry& r, u32 e) {
            r.remove<esengine::ecs::WorldTransform>(static_cast<Entity>(e));
        }))

        // Velocity
        .function("hasVelocity", optional_override([](Registry& r, u32 e) {
            return r.has<esengine::ecs::Velocity>(static_cast<Entity>(e));
        }))
        .function("getVelocity", optional_override([](Registry& r, u32 e) -> esengine::ecs::Velocity& {
            return r.get<esengine::ecs::Velocity>(static_cast<Entity>(e));
        }), allow_raw_pointers())
        .function("addVelocity", optional_override([](Registry& r, u32 e, const esengine::ecs::Velocity& c) {
            r.emplaceOrReplace<esengine::ecs::Velocity>(static_cast<Entity>(e), c);
        }))
        .function("removeVelocity", optional_override([](Registry& r, u32 e) {
            r.remove<esengine::ecs::Velocity>(static_cast<Entity>(e));
        }))

        // SpineAnimation
        .function("hasSpineAnimation", optional_override([](Registry& r, u32 e) {
            return r.has<esengine::ecs::SpineAnimation>(static_cast<Entity>(e));
        }))
        .function("getSpineAnimation", optional_override([](Registry& r, u32 e) -> esengine::ecs::SpineAnimation& {
            return r.get<esengine::ecs::SpineAnimation>(static_cast<Entity>(e));
        }), allow_raw_pointers())
        .function("addSpineAnimation", optional_override([](Registry& r, u32 e, const esengine::ecs::SpineAnimation& c) {
            r.emplaceOrReplace<esengine::ecs::SpineAnimation>(static_cast<Entity>(e), c);
        }))
        .function("removeSpineAnimation", optional_override([](Registry& r, u32 e) {
            r.remove<esengine::ecs::SpineAnimation>(static_cast<Entity>(e));
        }))

        // RigidBody
        .function("hasRigidBody", optional_override([](Registry& r, u32 e) {
            return r.has<esengine::ecs::RigidBody>(static_cast<Entity>(e));
        }))
        .function("getRigidBody", optional_override([](Registry& r, u32 e) {
            return rigidbodyToJS(r.get<esengine::ecs::RigidBody>(static_cast<Entity>(e)));
        }))
        .function("addRigidBody", optional_override([](Registry& r, u32 e, const RigidBodyJS& js) {
            r.emplaceOrReplace<esengine::ecs::RigidBody>(static_cast<Entity>(e), rigidbodyFromJS(js));
        }))
        .function("removeRigidBody", optional_override([](Registry& r, u32 e) {
            r.remove<esengine::ecs::RigidBody>(static_cast<Entity>(e));
        }))

        // BitmapText
        .function("hasBitmapText", optional_override([](Registry& r, u32 e) {
            return r.has<esengine::ecs::BitmapText>(static_cast<Entity>(e));
        }))
        .function("getBitmapText", optional_override([](Registry& r, u32 e) {
            return bitmaptextToJS(r.get<esengine::ecs::BitmapText>(static_cast<Entity>(e)));
        }))
        .function("addBitmapText", optional_override([](Registry& r, u32 e, const BitmapTextJS& js) {
            r.emplaceOrReplace<esengine::ecs::BitmapText>(static_cast<Entity>(e), bitmaptextFromJS(js));
        }))
        .function("removeBitmapText", optional_override([](Registry& r, u32 e) {
            r.remove<esengine::ecs::BitmapText>(static_cast<Entity>(e));
        }))

        // Sprite
        .function("hasSprite", optional_override([](Registry& r, u32 e) {
            return r.has<esengine::ecs::Sprite>(static_cast<Entity>(e));
        }))
        .function("getSprite", optional_override([](Registry& r, u32 e) {
            return spriteToJS(r.get<esengine::ecs::Sprite>(static_cast<Entity>(e)));
        }))
        .function("addSprite", optional_override([](Registry& r, u32 e, const SpriteJS& js) {
            r.emplaceOrReplace<esengine::ecs::Sprite>(static_cast<Entity>(e), spriteFromJS(js));
        }))
        .function("removeSprite", optional_override([](Registry& r, u32 e) {
            r.remove<esengine::ecs::Sprite>(static_cast<Entity>(e));
        }))

        // Parent
        .function("hasParent", optional_override([](Registry& r, u32 e) {
            return r.has<esengine::ecs::Parent>(static_cast<Entity>(e));
        }))
        .function("getParent", optional_override([](Registry& r, u32 e) -> esengine::ecs::Parent& {
            return r.get<esengine::ecs::Parent>(static_cast<Entity>(e));
        }), allow_raw_pointers())
        .function("addParent", optional_override([](Registry& r, u32 e, const esengine::ecs::Parent& c) {
            r.emplaceOrReplace<esengine::ecs::Parent>(static_cast<Entity>(e), c);
        }))
        .function("removeParent", optional_override([](Registry& r, u32 e) {
            r.remove<esengine::ecs::Parent>(static_cast<Entity>(e));
        }))

        // Children
        .function("hasChildren", optional_override([](Registry& r, u32 e) {
            return r.has<esengine::ecs::Children>(static_cast<Entity>(e));
        }))
        .function("getChildren", optional_override([](Registry& r, u32 e) -> esengine::ecs::Children& {
            return r.get<esengine::ecs::Children>(static_cast<Entity>(e));
        }), allow_raw_pointers())
        .function("addChildren", optional_override([](Registry& r, u32 e, const esengine::ecs::Children& c) {
            r.emplaceOrReplace<esengine::ecs::Children>(static_cast<Entity>(e), c);
        }))
        .function("removeChildren", optional_override([](Registry& r, u32 e) {
            r.remove<esengine::ecs::Children>(static_cast<Entity>(e));
        }))

        // Canvas
        .function("hasCanvas", optional_override([](Registry& r, u32 e) {
            return r.has<esengine::ecs::Canvas>(static_cast<Entity>(e));
        }))
        .function("getCanvas", optional_override([](Registry& r, u32 e) {
            return canvasToJS(r.get<esengine::ecs::Canvas>(static_cast<Entity>(e)));
        }))
        .function("addCanvas", optional_override([](Registry& r, u32 e, const CanvasJS& js) {
            r.emplaceOrReplace<esengine::ecs::Canvas>(static_cast<Entity>(e), canvasFromJS(js));
        }))
        .function("removeCanvas", optional_override([](Registry& r, u32 e) {
            r.remove<esengine::ecs::Canvas>(static_cast<Entity>(e));
        }))

        // Camera
        .function("hasCamera", optional_override([](Registry& r, u32 e) {
            return r.has<esengine::ecs::Camera>(static_cast<Entity>(e));
        }))
        .function("getCamera", optional_override([](Registry& r, u32 e) {
            return cameraToJS(r.get<esengine::ecs::Camera>(static_cast<Entity>(e)));
        }))
        .function("addCamera", optional_override([](Registry& r, u32 e, const CameraJS& js) {
            r.emplaceOrReplace<esengine::ecs::Camera>(static_cast<Entity>(e), cameraFromJS(js));
        }))
        .function("removeCamera", optional_override([](Registry& r, u32 e) {
            r.remove<esengine::ecs::Camera>(static_cast<Entity>(e));
        }))

        // Hierarchy Utilities
        .function("setParent", optional_override([](Registry& r, u32 child, u32 parent) {
            esengine::ecs::setParent(r, static_cast<Entity>(child), static_cast<Entity>(parent));
        }))

        ;
}

#endif  // ES_PLATFORM_WEB
