/**
 * @file    WebBindings.generated.cpp
 * @brief   Auto-generated Emscripten bindings
 * @details Generated by tools/generate_bindings.py - DO NOT EDIT MANUALLY
 *
 * @author  ESEngine Binding Generator
 * @date    2026
 */

#ifdef ES_PLATFORM_WEB

#include <emscripten/bind.h>
#include "../ecs/Registry.hpp"
#include "../ecs/Entity.hpp"
#include "../math/Math.hpp"

#include "../ecs/components/Camera.hpp"
#include "../ecs/components/Canvas.hpp"
#include "../ecs/components/Hierarchy.hpp"
#include "../ecs/components/Sprite.hpp"
#include "../ecs/components/Transform.hpp"
#include "../ecs/components/Velocity.hpp"

using namespace emscripten;

namespace esengine {

// =============================================================================
// Math Types
// =============================================================================

EMSCRIPTEN_BINDINGS(esengine_math) {
    // Vec2
    value_object<glm::vec2>("Vec2")
        .field("x", &glm::vec2::x)
        .field("y", &glm::vec2::y);

    // Vec3
    value_object<glm::vec3>("Vec3")
        .field("x", &glm::vec3::x)
        .field("y", &glm::vec3::y)
        .field("z", &glm::vec3::z);

    // Vec4
    value_object<glm::vec4>("Vec4")
        .field("x", &glm::vec4::x)
        .field("y", &glm::vec4::y)
        .field("z", &glm::vec4::z)
        .field("w", &glm::vec4::w);

    // Quat
    value_object<glm::quat>("Quat")
        .field("x", &glm::quat::x)
        .field("y", &glm::quat::y)
        .field("z", &glm::quat::z)
        .field("w", &glm::quat::w);
}

// =============================================================================
// ECS Entity Type
// =============================================================================

EMSCRIPTEN_BINDINGS(esengine_entity) {
    // Entity is u32, exposed as number in JavaScript
}

// =============================================================================
// ECS Components
// =============================================================================

EMSCRIPTEN_BINDINGS(esengine_components) {
    // Camera component
    value_object<esengine::ecs::Camera>("Camera")
        .field("projectionType", &esengine::ecs::Camera::projectionType)
        .field("fov", &esengine::ecs::Camera::fov)
        .field("orthoSize", &esengine::ecs::Camera::orthoSize)
        .field("nearPlane", &esengine::ecs::Camera::nearPlane)
        .field("farPlane", &esengine::ecs::Camera::farPlane)
        .field("aspectRatio", &esengine::ecs::Camera::aspectRatio)
        .field("isActive", &esengine::ecs::Camera::isActive)
        .field("priority", &esengine::ecs::Camera::priority)
        ;

    // Canvas component
    value_object<esengine::ecs::Canvas>("Canvas")
        .field("designResolution", &esengine::ecs::Canvas::designResolution)
        .field("pixelsPerUnit", &esengine::ecs::Canvas::pixelsPerUnit)
        .field("scaleMode", &esengine::ecs::Canvas::scaleMode)
        .field("matchWidthOrHeight", &esengine::ecs::Canvas::matchWidthOrHeight)
        .field("backgroundColor", &esengine::ecs::Canvas::backgroundColor)
        ;

    // Parent component
    value_object<esengine::ecs::Parent>("Parent")
        .field("entity", &esengine::ecs::Parent::entity)
        ;

    // Children component
    value_object<esengine::ecs::Children>("Children")
        ;

    // Sprite component
    value_object<esengine::ecs::Sprite>("Sprite")
        .field("texture", &esengine::ecs::Sprite::texture)
        .field("color", &esengine::ecs::Sprite::color)
        .field("size", &esengine::ecs::Sprite::size)
        .field("uvOffset", &esengine::ecs::Sprite::uvOffset)
        .field("uvScale", &esengine::ecs::Sprite::uvScale)
        .field("layer", &esengine::ecs::Sprite::layer)
        .field("flipX", &esengine::ecs::Sprite::flipX)
        .field("flipY", &esengine::ecs::Sprite::flipY)
        ;

    // LocalTransform component
    value_object<esengine::ecs::LocalTransform>("LocalTransform")
        .field("position", &esengine::ecs::LocalTransform::position)
        .field("rotation", &esengine::ecs::LocalTransform::rotation)
        .field("scale", &esengine::ecs::LocalTransform::scale)
        .field("matrix", &esengine::ecs::LocalTransform::matrix)
        .field("position", &esengine::ecs::LocalTransform::position)
        .field("rotation", &esengine::ecs::LocalTransform::rotation)
        .field("scale", &esengine::ecs::LocalTransform::scale)
        ;

    // WorldTransform component
    value_object<esengine::ecs::WorldTransform>("WorldTransform")
        .field("matrix", &esengine::ecs::WorldTransform::matrix)
        .field("position", &esengine::ecs::WorldTransform::position)
        .field("rotation", &esengine::ecs::WorldTransform::rotation)
        .field("scale", &esengine::ecs::WorldTransform::scale)
        ;

    // Velocity component
    value_object<esengine::ecs::Velocity>("Velocity")
        .field("linear", &esengine::ecs::Velocity::linear)
        .field("angular", &esengine::ecs::Velocity::angular)
        ;

}

// =============================================================================
// ECS Registry
// =============================================================================

EMSCRIPTEN_BINDINGS(esengine_registry) {
    class_<ecs::Registry>("Registry")
        .constructor<>()

        // Entity management
        .function("create", optional_override([](ecs::Registry& self) {
            return self.create();
        }))
        .function("destroy", optional_override([](ecs::Registry& self, Entity e) {
            self.destroy(e);
        }))
        .function("valid", optional_override([](ecs::Registry& self, Entity e) {
            return self.valid(e);
        }))
        .function("entityCount", optional_override([](const ecs::Registry& self) {
            return self.entityCount();
        }))

        // Camera component
        .function("hasCamera", optional_override([](ecs::Registry& self, Entity e) {
            return self.has<esengine::ecs::Camera>(e);
        }))
        .function("getCamera", optional_override([](ecs::Registry& self, Entity e) -> esengine::ecs::Camera& {
            return self.get<esengine::ecs::Camera>(e);
        }))
        .function("addCamera", optional_override([](ecs::Registry& self, Entity e, const esengine::ecs::Camera& c) -> esengine::ecs::Camera& {
            return self.emplaceOrReplace<esengine::ecs::Camera>(e, c);
        }))
        .function("removeCamera", optional_override([](ecs::Registry& self, Entity e) {
            self.remove<esengine::ecs::Camera>(e);
        }))

        // Canvas component
        .function("hasCanvas", optional_override([](ecs::Registry& self, Entity e) {
            return self.has<esengine::ecs::Canvas>(e);
        }))
        .function("getCanvas", optional_override([](ecs::Registry& self, Entity e) -> esengine::ecs::Canvas& {
            return self.get<esengine::ecs::Canvas>(e);
        }))
        .function("addCanvas", optional_override([](ecs::Registry& self, Entity e, const esengine::ecs::Canvas& c) -> esengine::ecs::Canvas& {
            return self.emplaceOrReplace<esengine::ecs::Canvas>(e, c);
        }))
        .function("removeCanvas", optional_override([](ecs::Registry& self, Entity e) {
            self.remove<esengine::ecs::Canvas>(e);
        }))

        // Parent component
        .function("hasParent", optional_override([](ecs::Registry& self, Entity e) {
            return self.has<esengine::ecs::Parent>(e);
        }))
        .function("getParent", optional_override([](ecs::Registry& self, Entity e) -> esengine::ecs::Parent& {
            return self.get<esengine::ecs::Parent>(e);
        }))
        .function("addParent", optional_override([](ecs::Registry& self, Entity e, const esengine::ecs::Parent& c) -> esengine::ecs::Parent& {
            return self.emplaceOrReplace<esengine::ecs::Parent>(e, c);
        }))
        .function("removeParent", optional_override([](ecs::Registry& self, Entity e) {
            self.remove<esengine::ecs::Parent>(e);
        }))

        // Children component
        .function("hasChildren", optional_override([](ecs::Registry& self, Entity e) {
            return self.has<esengine::ecs::Children>(e);
        }))
        .function("getChildren", optional_override([](ecs::Registry& self, Entity e) -> esengine::ecs::Children& {
            return self.get<esengine::ecs::Children>(e);
        }))
        .function("addChildren", optional_override([](ecs::Registry& self, Entity e, const esengine::ecs::Children& c) -> esengine::ecs::Children& {
            return self.emplaceOrReplace<esengine::ecs::Children>(e, c);
        }))
        .function("removeChildren", optional_override([](ecs::Registry& self, Entity e) {
            self.remove<esengine::ecs::Children>(e);
        }))

        // Sprite component
        .function("hasSprite", optional_override([](ecs::Registry& self, Entity e) {
            return self.has<esengine::ecs::Sprite>(e);
        }))
        .function("getSprite", optional_override([](ecs::Registry& self, Entity e) -> esengine::ecs::Sprite& {
            return self.get<esengine::ecs::Sprite>(e);
        }))
        .function("addSprite", optional_override([](ecs::Registry& self, Entity e, const esengine::ecs::Sprite& c) -> esengine::ecs::Sprite& {
            return self.emplaceOrReplace<esengine::ecs::Sprite>(e, c);
        }))
        .function("removeSprite", optional_override([](ecs::Registry& self, Entity e) {
            self.remove<esengine::ecs::Sprite>(e);
        }))

        // LocalTransform component
        .function("hasLocalTransform", optional_override([](ecs::Registry& self, Entity e) {
            return self.has<esengine::ecs::LocalTransform>(e);
        }))
        .function("getLocalTransform", optional_override([](ecs::Registry& self, Entity e) -> esengine::ecs::LocalTransform& {
            return self.get<esengine::ecs::LocalTransform>(e);
        }))
        .function("addLocalTransform", optional_override([](ecs::Registry& self, Entity e, const esengine::ecs::LocalTransform& c) -> esengine::ecs::LocalTransform& {
            return self.emplaceOrReplace<esengine::ecs::LocalTransform>(e, c);
        }))
        .function("removeLocalTransform", optional_override([](ecs::Registry& self, Entity e) {
            self.remove<esengine::ecs::LocalTransform>(e);
        }))

        // WorldTransform component
        .function("hasWorldTransform", optional_override([](ecs::Registry& self, Entity e) {
            return self.has<esengine::ecs::WorldTransform>(e);
        }))
        .function("getWorldTransform", optional_override([](ecs::Registry& self, Entity e) -> esengine::ecs::WorldTransform& {
            return self.get<esengine::ecs::WorldTransform>(e);
        }))
        .function("addWorldTransform", optional_override([](ecs::Registry& self, Entity e, const esengine::ecs::WorldTransform& c) -> esengine::ecs::WorldTransform& {
            return self.emplaceOrReplace<esengine::ecs::WorldTransform>(e, c);
        }))
        .function("removeWorldTransform", optional_override([](ecs::Registry& self, Entity e) {
            self.remove<esengine::ecs::WorldTransform>(e);
        }))

        // Velocity component
        .function("hasVelocity", optional_override([](ecs::Registry& self, Entity e) {
            return self.has<esengine::ecs::Velocity>(e);
        }))
        .function("getVelocity", optional_override([](ecs::Registry& self, Entity e) -> esengine::ecs::Velocity& {
            return self.get<esengine::ecs::Velocity>(e);
        }))
        .function("addVelocity", optional_override([](ecs::Registry& self, Entity e, const esengine::ecs::Velocity& c) -> esengine::ecs::Velocity& {
            return self.emplaceOrReplace<esengine::ecs::Velocity>(e, c);
        }))
        .function("removeVelocity", optional_override([](ecs::Registry& self, Entity e) {
            self.remove<esengine::ecs::Velocity>(e);
        }))

        ;
}

}  // namespace esengine

#endif  // ES_PLATFORM_WEB
