/**
 * @file    esengine.d.ts
 * @brief   TypeScript definitions for ESEngine
 * @details Generated by tools/generate_bindings.py - DO NOT EDIT MANUALLY
 */

declare namespace Module {
    // =============================================================================
    // Core Types
    // =============================================================================

    type Entity = number;

    // =============================================================================
    // Math Types
    // =============================================================================

    interface Vec2 {
        x: number;
        y: number;
    }

    interface Vec3 {
        x: number;
        y: number;
        z: number;
    }

    interface Vec4 {
        x: number;
        y: number;
        z: number;
        w: number;
    }

    interface Quat {
        x: number;
        y: number;
        z: number;
        w: number;
    }

    // =============================================================================
    // ECS Components
    // =============================================================================

    interface Camera {
        projectionType: any;
        fov: number;
        orthoSize: number;
        nearPlane: number;
        farPlane: number;
        aspectRatio: number;
        isActive: boolean;
        priority: number;
    }

    interface Canvas {
        designResolution: any;
        pixelsPerUnit: number;
        scaleMode: any;
        matchWidthOrHeight: number;
        backgroundColor: Vec4;
    }

    interface Parent {
        entity: Entity;
    }

    interface Children {
    }

    interface Sprite {
        texture: any;
        color: Vec4;
        size: Vec2;
        uvOffset: Vec2;
        uvScale: Vec2;
        layer: number;
        flipX: boolean;
        flipY: boolean;
    }

    interface LocalTransform {
        position: Vec3;
        rotation: Quat;
        scale: Vec3;
        matrix: any;
        position: Vec3;
        rotation: Quat;
        scale: Vec3;
    }

    interface WorldTransform {
        matrix: any;
        position: Vec3;
        rotation: Quat;
        scale: Vec3;
    }

    interface Velocity {
        linear: Vec3;
        angular: Vec3;
    }

    // =============================================================================
    // ECS Registry
    // =============================================================================

    class Registry {
        constructor();

        // Entity management
        create(): Entity;
        destroy(entity: Entity): void;
        valid(entity: Entity): boolean;
        entityCount(): number;

        // Camera component
        hasCamera(entity: Entity): boolean;
        getCamera(entity: Entity): Camera;
        addCamera(entity: Entity, component: Camera): Camera;
        removeCamera(entity: Entity): void;

        // Canvas component
        hasCanvas(entity: Entity): boolean;
        getCanvas(entity: Entity): Canvas;
        addCanvas(entity: Entity, component: Canvas): Canvas;
        removeCanvas(entity: Entity): void;

        // Parent component
        hasParent(entity: Entity): boolean;
        getParent(entity: Entity): Parent;
        addParent(entity: Entity, component: Parent): Parent;
        removeParent(entity: Entity): void;

        // Children component
        hasChildren(entity: Entity): boolean;
        getChildren(entity: Entity): Children;
        addChildren(entity: Entity, component: Children): Children;
        removeChildren(entity: Entity): void;

        // Sprite component
        hasSprite(entity: Entity): boolean;
        getSprite(entity: Entity): Sprite;
        addSprite(entity: Entity, component: Sprite): Sprite;
        removeSprite(entity: Entity): void;

        // LocalTransform component
        hasLocalTransform(entity: Entity): boolean;
        getLocalTransform(entity: Entity): LocalTransform;
        addLocalTransform(entity: Entity, component: LocalTransform): LocalTransform;
        removeLocalTransform(entity: Entity): void;

        // WorldTransform component
        hasWorldTransform(entity: Entity): boolean;
        getWorldTransform(entity: Entity): WorldTransform;
        addWorldTransform(entity: Entity, component: WorldTransform): WorldTransform;
        removeWorldTransform(entity: Entity): void;

        // Velocity component
        hasVelocity(entity: Entity): boolean;
        getVelocity(entity: Entity): Velocity;
        addVelocity(entity: Entity, component: Velocity): Velocity;
        removeVelocity(entity: Entity): void;

    }

    // =============================================================================
    // Module Lifecycle
    // =============================================================================

    function onRuntimeInitialized(): void;
}

export = Module;
export as namespace Module;
