/**
 * @file    esengine.d.ts
 * @brief   ESEngine TypeScript Definitions
 * @details Generated by EHT (ESEngine Header Tool) - DO NOT EDIT
 *
 * @author  ESEngine Team
 * @date    2026
 *
 * @copyright Copyright (c) 2026 ESEngine Team
 *            Licensed under the MIT License.
 */

// =============================================================================
// Core Types
// =============================================================================

export type Entity = number;

// =============================================================================
// Math Types
// =============================================================================

export interface Vec2 { x: number; y: number; }
export interface Vec3 { x: number; y: number; z: number; }
export interface Vec4 { x: number; y: number; z: number; w: number; }
export interface UVec2 { x: number; y: number; }
export interface Quat { w: number; x: number; y: number; z: number; }
export type Mat4 = number[];

// =============================================================================
// Enums
// =============================================================================

export const enum ProjectionType {
    Perspective = 0,
    Orthographic = 1
}

export const enum CanvasScaleMode {
    FixedWidth = 0,
    FixedHeight = 1,
    Expand = 2,
    Shrink = 3,
    Match = 4
}

// =============================================================================
// Components
// =============================================================================

export interface Camera {
    projectionType: ProjectionType;
    fov: number;
    orthoSize: number;
    nearPlane: number;
    farPlane: number;
    aspectRatio: number;
    isActive: boolean;
    priority: number;
}

export interface Canvas {
    designResolution: UVec2;
    pixelsPerUnit: number;
    scaleMode: CanvasScaleMode;
    matchWidthOrHeight: number;
    backgroundColor: Vec4;
}

export interface Parent {
    entity: number;
}

export interface Children {
    entities: Entity[];
}

export interface Sprite {
    texture: number;
    color: Vec4;
    size: Vec2;
    uvOffset: Vec2;
    uvScale: Vec2;
    layer: number;
    flipX: boolean;
    flipY: boolean;
}

export interface LocalTransform {
    position: Vec3;
    rotation: Quat;
    scale: Vec3;
}

export interface WorldTransform {
    matrix: Mat4;
    position: Vec3;
    rotation: Quat;
    scale: Vec3;
}

export interface Velocity {
    linear: Vec3;
    angular: Vec3;
}

// =============================================================================
// Registry
// =============================================================================

export interface Registry {
    create(): Entity;
    destroy(entity: Entity): void;
    valid(entity: Entity): boolean;
    entityCount(): number;

    hasCamera(entity: Entity): boolean;
    getCamera(entity: Entity): Camera;
    addCamera(entity: Entity, component: Camera): void;
    removeCamera(entity: Entity): void;

    hasCanvas(entity: Entity): boolean;
    getCanvas(entity: Entity): Canvas;
    addCanvas(entity: Entity, component: Canvas): void;
    removeCanvas(entity: Entity): void;

    hasParent(entity: Entity): boolean;
    getParent(entity: Entity): Parent;
    addParent(entity: Entity, component: Parent): void;
    removeParent(entity: Entity): void;

    hasChildren(entity: Entity): boolean;
    getChildren(entity: Entity): Children;
    addChildren(entity: Entity, component: Children): void;
    removeChildren(entity: Entity): void;

    hasSprite(entity: Entity): boolean;
    getSprite(entity: Entity): Sprite;
    addSprite(entity: Entity, component: Sprite): void;
    removeSprite(entity: Entity): void;

    hasLocalTransform(entity: Entity): boolean;
    getLocalTransform(entity: Entity): LocalTransform;
    addLocalTransform(entity: Entity, component: LocalTransform): void;
    removeLocalTransform(entity: Entity): void;

    hasWorldTransform(entity: Entity): boolean;
    getWorldTransform(entity: Entity): WorldTransform;
    addWorldTransform(entity: Entity, component: WorldTransform): void;
    removeWorldTransform(entity: Entity): void;

    hasVelocity(entity: Entity): boolean;
    getVelocity(entity: Entity): Velocity;
    addVelocity(entity: Entity, component: Velocity): void;
    removeVelocity(entity: Entity): void;

    [key: string]: unknown;
}

// =============================================================================
// Resource Types
// =============================================================================

export type ShaderHandle = number;
export type TextureHandle = number;

export const enum TextureFormat {
    RGB8 = 0,
    RGBA8 = 1
}

export interface ResourceManager {
    init(): void;
    shutdown(): void;
    createShader(vertSrc: string, fragSrc: string): ShaderHandle;
    createTexture(width: number, height: number, pixelsPtr: number, pixelsLen: number, format: TextureFormat): TextureHandle;
    releaseShader(handle: ShaderHandle): void;
    releaseTexture(handle: TextureHandle): void;
}

// =============================================================================
// App Types
// =============================================================================

export const enum Schedule {
    Startup = 0,
    PreUpdate = 1,
    Update = 2,
    PostUpdate = 3,
    PreRender = 4,
    Render = 5,
    PostRender = 6,
}

export interface Time {
    delta: number;
    elapsed: number;
    frameCount: number;
}

export interface AppConfig {
    title: string;
    width: number;
    height: number;
    vsync: boolean;
}

export interface NativeApp {
    run(): void;
    quit(): void;
    registry(): Registry;
    time(): Time;
    width(): number;
    height(): number;
}

// =============================================================================
// Query Types
// =============================================================================

export interface EntityVector {
    size(): number;
    get(index: number): Entity;
}

// =============================================================================
// Module
// =============================================================================

export interface ESEngineModule {
    ResourceManager: new () => ResourceManager;
    AppConfig: new () => AppConfig;

    Camera: new () => Camera;
    Canvas: new () => Canvas;
    Parent: new () => Parent;
    Children: new () => Children;
    Sprite: new () => Sprite;
    LocalTransform: new () => LocalTransform;
    WorldTransform: new () => WorldTransform;
    Velocity: new () => Velocity;

    Schedule: typeof Schedule;
    TextureFormat: typeof TextureFormat;
    ProjectionType: typeof ProjectionType;
    CanvasScaleMode: typeof CanvasScaleMode;

    createApp(): NativeApp;
    createAppWithConfig(config: AppConfig): NativeApp;
    getApp(): NativeApp;

    queryLocalTransform(registry: Registry): EntityVector;
    queryLocalTransformSprite(registry: Registry): EntityVector;

    HEAPU8: Uint8Array;
    _malloc(size: number): number;
    _free(ptr: number): void;

    setJSSystemsCallback(callback: (schedule: number, dt: number) => void): void;

    [key: string]: unknown;
}

export default function createModule(): Promise<ESEngineModule>;
