import { ServiceToken } from './ServiceToken';
import type { ComponentSchema } from '../schemas/ComponentSchemas';
import type { PropertyEditorFactory } from '../property/PropertyEditor';
import type { BoundsProvider } from '../bounds/BoundsProvider';
import type { GizmoDescriptor } from '../gizmos/GizmoRegistry';
import type { PanelDescriptor } from '../panels/PanelRegistry';
import type { MenuDescriptor, MenuItemDescriptor, StatusbarItemDescriptor } from '../menus/MenuRegistry';
import type { SettingsSectionDescriptor, SettingsGroupDescriptor, SettingsItemDescriptor } from '../settings/SettingsRegistry';
import type { ContextMenuContribution } from '../ui/ContextMenuRegistry';
import type { InspectorSectionDescriptor, ComponentInspectorDescriptor } from '../panels/inspector/InspectorRegistry';
import type { AssetTypeDescriptor } from '../asset/AssetTypeRegistry';
import type { AssetEventBus } from '../events/AssetEventBus';
import type { AssetDependencyGraph } from '../asset/AssetDependencyGraph';
import type { ImporterRegistryImpl } from '../asset/ImporterRegistry';
import type { AssetPathResolver } from '../asset/AssetPathResolver';
import type { EditorStore } from '../store/EditorStore';
import type { SharedRenderContext } from '../renderer/SharedRenderContext';
import type { AssetDatabase } from '../asset/AssetDatabase';
import type { PlayModeService } from '../services/PlayModeService';

export const COMPONENT_SCHEMA = new ServiceToken<ComponentSchema>('COMPONENT_SCHEMA');
export const PROPERTY_EDITOR = new ServiceToken<PropertyEditorFactory>('PROPERTY_EDITOR');
export const BOUNDS_PROVIDER = new ServiceToken<BoundsProvider>('BOUNDS_PROVIDER');
export const GIZMO = new ServiceToken<GizmoDescriptor>('GIZMO');
export const PANEL = new ServiceToken<PanelDescriptor>('PANEL');
export const MENU = new ServiceToken<MenuDescriptor>('MENU');
export const MENU_ITEM = new ServiceToken<MenuItemDescriptor>('MENU_ITEM');
export const STATUSBAR_ITEM = new ServiceToken<StatusbarItemDescriptor>('STATUSBAR_ITEM');
export const SETTINGS_SECTION = new ServiceToken<SettingsSectionDescriptor>('SETTINGS_SECTION');
export const SETTINGS_GROUP = new ServiceToken<SettingsGroupDescriptor>('SETTINGS_GROUP');
export const SETTINGS_ITEM = new ServiceToken<SettingsItemDescriptor>('SETTINGS_ITEM');
export const CONTEXT_MENU_ITEM = new ServiceToken<ContextMenuContribution>('CONTEXT_MENU_ITEM');
export const INSPECTOR_SECTION = new ServiceToken<InspectorSectionDescriptor>('INSPECTOR_SECTION');
export const COMPONENT_INSPECTOR = new ServiceToken<ComponentInspectorDescriptor>('COMPONENT_INSPECTOR');
export const ASSET_TYPE = new ServiceToken<AssetTypeDescriptor>('ASSET_TYPE');
export const ASSET_EDITOR_TYPE = new ServiceToken<string>('ASSET_EDITOR_TYPE');
export const ASSET_EVENT_BUS = new ServiceToken<AssetEventBus>('ASSET_EVENT_BUS');
export const ASSET_DEP_GRAPH = new ServiceToken<AssetDependencyGraph>('ASSET_DEP_GRAPH');
export const IMPORTER_REGISTRY = new ServiceToken<ImporterRegistryImpl>('IMPORTER_REGISTRY');
export const GLOBAL_PATH_RESOLVER = new ServiceToken<AssetPathResolver>('GLOBAL_PATH_RESOLVER');
export const EDITOR_STORE = new ServiceToken<EditorStore>('EDITOR_STORE');
export const SHARED_RENDER_CTX = new ServiceToken<SharedRenderContext>('SHARED_RENDER_CTX');
export const ASSET_DATABASE = new ServiceToken<AssetDatabase>('ASSET_DATABASE');
export const PLAY_MODE_SERVICE = new ServiceToken<PlayModeService>('PLAY_MODE_SERVICE');

export interface ComponentLifecycle {
    remove(world: any, entity: any, entityId: number): void;
}
export const COMPONENT_LIFECYCLE = new ServiceToken<ComponentLifecycle>('COMPONENT_LIFECYCLE');

export const SCENE_SERVICE = new ServiceToken<any>('SCENE_SERVICE');
export const CLIPBOARD_SERVICE = new ServiceToken<any>('CLIPBOARD_SERVICE');
export const PREVIEW_SERVICE = new ServiceToken<any>('PREVIEW_SERVICE');
export const SCRIPT_SERVICE = new ServiceToken<any>('SCRIPT_SERVICE');
export const EXTENSION_SERVICE = new ServiceToken<any>('EXTENSION_SERVICE');
export const SHELL_SERVICE = new ServiceToken<any>('SHELL_SERVICE');
export const PROFILER_SERVICE = new ServiceToken<any>('PROFILER_SERVICE');
export const LAYOUT_SERVICE = new ServiceToken<any>('LAYOUT_SERVICE');
export const NAVIGATION_SERVICE = new ServiceToken<any>('NAVIGATION_SERVICE');
export const OUTPUT_SERVICE = new ServiceToken<any>('OUTPUT_SERVICE');
export const SPINE_SERVICE = new ServiceToken<any>('SPINE_SERVICE');
export const RUNTIME_SERVICE = new ServiceToken<any>('RUNTIME_SERVICE');
export const MULTI_WINDOW_SERVICE = new ServiceToken<any>('MULTI_WINDOW_SERVICE');
export const PROJECT_SERVICE = new ServiceToken<any>('PROJECT_SERVICE');
export const PLUGIN_MANAGER = new ServiceToken<any>('PLUGIN_MANAGER');
