// ESEngine WeChat MiniGame Entry Point

import './weapp-adapter.js';

// Get system info
const systemInfo = wx.getSystemInfoSync();
const dpr = systemInfo.pixelRatio;
const width = systemInfo.windowWidth * dpr;
const height = systemInfo.windowHeight * dpr;

// Create canvas
const canvas = wx.createCanvas();
canvas.width = width;
canvas.height = height;

// Set up WebGL context
const gl = canvas.getContext('webgl2') || canvas.getContext('webgl');

if (!gl) {
    console.error('WebGL not supported');
}

// Module configuration
var Module = {
    canvas: canvas,
    gl: gl,
    print: function(text) {
        console.log('[ESEngine]', text);
    },
    printErr: function(text) {
        console.error('[ESEngine]', text);
    },
    onRuntimeInitialized: function() {
        console.log('ESEngine initialized');
        // Initialize engine
        if (Module._es_init) {
            Module._es_init(width, height);
        }
        // Start game loop
        startGameLoop();
    }
};

// Touch handling
let touches = new Map();

canvas.addEventListener('touchstart', (e) => {
    for (let touch of e.changedTouches) {
        touches.set(touch.identifier, {
            x: touch.clientX * dpr,
            y: touch.clientY * dpr
        });
        if (Module._es_on_touch) {
            Module._es_on_touch(0, touch.clientX * dpr, touch.clientY * dpr);
        }
    }
});

canvas.addEventListener('touchmove', (e) => {
    for (let touch of e.changedTouches) {
        touches.set(touch.identifier, {
            x: touch.clientX * dpr,
            y: touch.clientY * dpr
        });
        if (Module._es_on_touch) {
            Module._es_on_touch(1, touch.clientX * dpr, touch.clientY * dpr);
        }
    }
});

canvas.addEventListener('touchend', (e) => {
    for (let touch of e.changedTouches) {
        if (Module._es_on_touch) {
            Module._es_on_touch(2, touch.clientX * dpr, touch.clientY * dpr);
        }
        touches.delete(touch.identifier);
    }
});

canvas.addEventListener('touchcancel', (e) => {
    for (let touch of e.changedTouches) {
        if (Module._es_on_touch) {
            Module._es_on_touch(3, touch.clientX * dpr, touch.clientY * dpr);
        }
        touches.delete(touch.identifier);
    }
});

// Game loop
let lastTime = Date.now();

function startGameLoop() {
    const loop = () => {
        const now = Date.now();
        const deltaTime = (now - lastTime) / 1000.0;
        lastTime = now;

        if (Module._es_update) {
            Module._es_update(deltaTime);
        }
        if (Module._es_render) {
            Module._es_render();
        }

        requestAnimationFrame(loop);
    };

    requestAnimationFrame(loop);
}

// Load the WASM module
// The esengine.js file should be generated by Emscripten
require('./esengine.js');
