export const TEXT_PADDING_RATIO = 0.2;
export const TEXT_CANVAS_SHRINK_FRAMES = 60;
export const TEXT_CANVAS_OVERSIZE_RATIO = 4;

export const TEXT_INPUT_LINE_HEIGHT_RATIO = 1.2;
export const CURSOR_BLINK_INTERVAL = 0.5;

export const SCROLL_WHEEL_SENSITIVITY = 0.1;
export const SCROLL_MAX_DT = 0.05;
export const SCROLL_VELOCITY_THRESHOLD = 0.1;
export const SCROLL_VELOCITY_LERP_SPEED = 10;
export const SCROLL_ELASTIC_SMOOTH_TIME = 0.1;
export const SCROLL_ELASTIC_SNAP_THRESHOLD = 0.5;
export const SCROLL_MAX_OVERSCROLL_RATIO = 0.5;
export const SCROLL_MAX_VELOCITY_RATIO = 5;
export const SCROLL_POSITION_EPSILON = 0.01;

export const DROPDOWN_ITEM_HEIGHT = 30;
export const DROPDOWN_FONT_SIZE = 16;
export const DROPDOWN_HIGHLIGHT_COLOR = { r: 0.3, g: 0.5, b: 0.8, a: 1 };
